### ISSUE TITLE
Load more posters

### ISSUE THREAD

**Issue by stargatehome** [wpmovielibrary/wpmovielibrary#145]
Hey Charlie,

it would be nice to have a button like the images have (load more posters). ;)

Mario

Not quite sure if i mention it yet haven't found such a post. :)

![unbenannt](https://cloud.githubusercontent.com/assets/9327486/5050616/eb0bdc8c-6c2f-11e4-9ad7-281ef97efd56.JPG)

**Comment by CaerCam** [comment]
Looking good! Version 2.2 will support multiple Posters import just like images. No "See available Movie Posters", everything happens in the "Posters" tab of the metabox where posters can be imported, deleted, edited and set as featured.

![Updated metabox panel](https://cloud.githubusercontent.com/assets/621662/5987705/70fb19c4-a93a-11e4-967d-faa6be5ce403.png)
![Importing a new poster](https://cloud.githubusercontent.com/assets/621662/5987706/70febd68-a93a-11e4-9305-b9d3099ea490.png)
![Setting as featured](https://cloud.githubusercontent.com/assets/621662/5987707/71010168-a93a-11e4-868d-3b5bff2a9910.png)

**Comment by stargatehome** [comment]
Great. :D Really love that.
