### ISSUE TITLE
ready to translate?

### ISSUE THREAD

**Issue by stargatehome** [wpmovielibrary/wpmovielibrary#173]
Hey Charlie,

is the actual version ready to translate into german?

Mario

**Comment by andreymil** [comment]
Hi Charlie, how to translate the public part to Russian? for example http://dubfilm.com/movies/terminator-genezis/  words such as: Storyline, Photos, Details and others...

**Comment by CaerCam** [comment]
Hi @andreymil, just copy the [`wpmovielibrary.pot`](https://github.com/wpmovielibrary/wpmovielibrary/blob/master/languages/wpmovielibrary.pot) file to `languages/wpmovielibrary-ru_RU.po` and edit it with [Poedit](http://poedit.com/)!

**Comment by andreymil** [comment]
Thanks, you helped me a lot.
