### ISSUE TITLE
Combination Genres

### ISSUE THREAD

**Issue by alexg1805** [wpmovielibrary/wpmovielibrary#175]
Since my update to Version 2.x wordpress shows combined genres in my automatically generated list of genres. Unfortunately movies with combined tags do not show under the parent gernre.
So a movie with ThrillerAction does not show under "Action" or "Thriller" only under "ThrillerAction".

Is this intended or a bug?
I would like to use genres intuitive.

**Comment by CaerCam** [comment]
Closed due to inactivity, reopen if needed.
