### ISSUE TITLE
JavaScript Backbone.js implementation

### ISSUE THREAD

**Issue by CaerCam** [wpmovielibrary/wpmovielibrary#180]
Started a couple days ago on the [backbone-dev branch](https://github.com/wpmovielibrary/wpmovielibrary/tree/backbone-dev), that's a major step for version 2.2: the plugin's JavaScript part will be completely rewritten to use Backbone. Not much to see for the regular user, but the code will be so much better to develop and maintain that it's not even an option not to use it.

**Comment by CaerCam** [comment]
@wpmovielibrary/testers I know I'm pretty slow to answer/push updates on master these days, but here's a look at wthat's going on right now. I don't how many of you follow the plugin on social networks, so this is a preview of what I'll release there later. This is why this ticket is very important :sunglasses:

How the "All Movies" page will look like in version 2.2, instead of the WP-ish, table-based view:

![allmovies](https://cloud.githubusercontent.com/assets/621662/6641951/76ee7006-c9a1-11e4-93c3-0d9eaad3d4b6.png)
![previewmodal](https://cloud.githubusercontent.com/assets/621662/6641953/76f5d346-c9a1-11e4-877e-5270f62ed8c0.png)
![editmodal](https://cloud.githubusercontent.com/assets/621662/6641954/76f6f03c-c9a1-11e4-81db-f0f0612d0584.png)

Furthermore, the importer will now be a part of the "All Movies" instead of the dedicated page:

![importer](https://cloud.githubusercontent.com/assets/621662/6641952/76f282f4-c9a1-11e4-8ccc-a8688a63813d.png)

**Comment by Ravavamouna** [comment]
Ah ben finalement tu t'es bien inspiré de TMDb !! Je trouve ça très clair
et le point positif c'est l'affiche qui apparaît en entier sur la page du
film.

2015-03-13 16:57 GMT+01:00 Charlie Merland <notifications@github.com>:

**Comment by CaerCam** [comment]
L'énorme avantage, en fait, sera de pouvoir faire un bon nombre d'opérations depuis la même page, notamment importer des films et les modifier facilement sans devoir jongler entre différentes pages... Le tout avec un design plutôt sympa qui simplifiera beaucoup la partie administration du plugin :-)

**Comment by Ravavamouna** [comment]
Tu me fais très plaisir en parlant de gain de temps. Je suis vraiment
impatiente de voir ça. Et est-ce que l'option des taxonomies étendues aux
pages et aux articles sera disponible dès la version 2 ou il faudra
attendre la prochaine mise à jour ?

**Comment by stargatehome** [comment]
Great! Like the new view. :)

**Comment by lapinzed** [comment]
Cool!! Hâte de tester ça:-)
