### ISSUE TITLE
Extra checking on movie import

### ISSUE THREAD

**Issue by CaerCam** [wpmovielibrary/wpmovielibrary#184]
Importing a movie can create duplicates of the imported title does not exactly match the already imported movie; extra checking should be added when manually of automatically importing data. Set to version 2.2 to use Backbone.

**Comment by kutluhanaykut** [comment]
It is vital when creating larger databases with batch import. I also had this duplicate entry issue.
I found this plugin to clean up.. And it seem to work fluently. (Supports custom fields)
https://wordpress.org/plugins/delete-duplicate-data/

I checkmarked "movie" custom post type and removed all duplicate data accordingly to trash bin in a single click from 2000 movie database..

Until we can get a better title and detail check for the import i suggest we may use this plugin..
