### ISSUE TITLE
IMDB Rating as a custom field

### ISSUE THREAD

**Issue by alexg1805** [wpmovielibrary/wpmovielibrary#201]
In one of the recent updates, I think, WPML gained the possibility to display the IMDB id. (tt123456789)

I wonder if it is possible to import the imdb (not tmdb!) ratings for my movies via any script to be able to display them as a custom field or similar?

Thank you in advance!

**Comment by CaerCam** [comment]
IMDb ID was indeed added to the list of available meta by 7ada74f9c2c33bfebc861d9608fefb4995bb8568 on October 24th, along with certification, budget, revenue, tagline, adult and homepage meta :)

That being said, it's not possible to import IMDb rating using the plugin. The IMDb ID is just part of the data available on TMDb, it does not link directly to the IMDb API (which by the way is not public, that's one of the reasons why the plugin is using TMDb API instead). What you're asking is not technically impossible to do, but would require a way to connect and use an IMDb API like [OMDb API](http://www.omdbapi.com), extract the ratings and save them in a custom field. But for now there's no way to do this in the same time that the plugin fetches the data from TMDb, so it would need to be a parallel process that would somehow be triggered when the data from TMDb are returned. In less words: doable, but very complicated to do it cleanly.

**Comment by alexg1805** [comment]
The IMDB Rating (at least for somewhat older movies) is kind of a very good indicator for unseen movies for me.

So as I understand, one would need an external script/plugin that uses the IMDB-ID in the meta to find the recent IMDB-rating via the API and store ist as a custom field.

This sounds a bit more advanced than my coding skills, but thank you anyways ;-)

**Comment by CaerCam** [comment]
Yes, that's pretty advanced programming :) It's not _that_ complicated per se to get the ratings, basically it would only require to use [`wp_remote_get()`](http://codex.wordpress.org/Function_Reference/wp_remote_get) on URLs like `http://www.omdbapi.com/?i=tt1182345&plot=short&r=json` to get the movie's IMDb data, [`json_decode()`](php.net/manual/fr/function.json-decode.php) to convert the data to PHP array, extract the rating, [`update_post_meta()`](http://codex.wordpress.org/update_post_meta) to save the data.

It gets more complicated to run this _after_ data where pulled from TMDb; it's not possible right now, but that's something fitting perfectly the description of #52, so I will implement it so developers can run code before and after data are fetched from TMDb, and that part requires some deeper knowledge of WordPress Action and Filter hooks.
