### ISSUE TITLE
Headbox problem

### ISSUE THREAD

**Issue by Fjellz** [wpmovielibrary/wpmovielibrary#202]
I dont know how long the problems has been there but now when i pick a genre like comedy. All my language and subtitles are gone. But when i pick the same movie on my site directly then i can see all the information.

![image](https://cloud.githubusercontent.com/assets/9780900/5592881/2b01778c-91e9-11e4-939f-3c5ba2aa7335.png)

![image](https://cloud.githubusercontent.com/assets/9780900/5592883/3c1eeae0-91e9-11e4-8677-a6c9016c67e4.png)

And one my question. Is it possible to make custom icon on movie media.

thx :)

**Comment by CaerCam** [comment]
Nice catch, should be fixed!

And no, for consistency media (as well as any other data) can not be displayed as icons in the headbox content; but they do appear as icons in the headbox header, like you can see below the title and genres :)

**Comment by Fjellz** [comment]
I mean the icon. i found out that the icon came from a font file. is it possible to edit that.

![image](https://cloud.githubusercontent.com/assets/9780900/5597055/0923ed94-929c-11e4-9112-70c7b40abc28.png)

I have tried but nothing happens when i overwrite the file.

**Comment by Fjellz** [comment]
Maybe i could be possible to making sound format: 5.1 DD 2.0 DD DTS... and so on with icon. 

And there could be more options with movie media. DVD, Custom DVD, BluRay Rip, DVD Rip. DVD Screener, HD Rip, WEB-DL

**Comment by CaerCam** [comment]
Oh, I didn't get that, sorry.

I tried to edit the font using FontForge, seems to work; be sure to clear your browser's cache and export the font in WOFF and TTF as well as SVG.

As for the additional media and sound, that's entirely possible using filters. The experimental [details](https://github.com/wpmovielibrary/wpmovielibrary-details) plugin is an example of what can be done to extend the list of the details/details values
