### ISSUE TITLE
WP Post Type change

### ISSUE THREAD

**Issue by hernangsoto** [wpmovielibrary/wpmovielibrary#203]
Hi! That's my question. The plugin creates a post type called 'movies' but i wanna use the movie database functionality with another or existing post type in my theme's. How can I do?
Thanks!
Greetings from Argentina

Hernan

**Comment by CaerCam** [comment]
Hi Hernan,

I guess it depends on which features you want to have, but in its current state the plugin is not built to work with other post types. With some edits you could use the metabox in other post types editor pages, but you will most likely run into trouble with most of the rest of the features. I wouldn't recommend this kind of hack unless you're really sure of what you're doing :wink:

**Comment by CaerCam** [comment]
Closed due to inactivity, reopen if needed.
