### ISSUE TITLE
Actors?

### ISSUE THREAD

**Issue by stargatehome** [wpmovielibrary/wpmovielibrary#204]
Hey Charlie,

there is a problem with using the actors. It imports it as "tags" but not in the new metadata-field so it doesn't show up. 
![unbenannt](https://cloud.githubusercontent.com/assets/9327486/5624517/6eee2f72-9567-11e4-98ca-345bf8944997.JPG)
Working on a new feature? :D 

Cheers, 
Mario

**Comment by CaerCam** [comment]
Ah, looks like a side-effect of [this bug](https://wordpress.org/support/topic/212-conflict-with-woocommerce-and-other-plugins)'s fix… I'll take a deeper look at it!

**Comment by CaerCam** [comment]
There seems to be an issue with the Advanced Rating plugin: once deactivated actors save just fine, but when activated actors are not saved anymore. Investigating!

**Comment by stargatehome** [comment]
:) Ok, was weird.
