### ISSUE TITLE
Links in detailed section 

### ISSUE THREAD

**Issue by leetaewon** [wpmovielibrary/wpmovielibrary#205]
Hi, Charlie~.
Thank you for a good plugin.

1) Composer have links but Directors don't.
But the URL works,
like http://cinetalk.kr/movies/director/john-ford/

Please Include links to directors.
Or, do I miss something? (Can I set the option on somewhere?)

2) Would you remove a link on opening date.
I don't need that, and it doesn't work.

Sincerely. :)

![wpml04](https://cloud.githubusercontent.com/assets/6120624/5626330/5c48b0c0-95cd-11e4-91a4-1ef2ab673e15.png)

**Comment by CaerCam** [comment]
1) Directors links rely on collections, if you had a "Lewis Milestone" collection there would be a link to it. But it is planned to add a fallback to meta in case there's no matching collection (as for actors and genre, btw), it should be in version 2.2.

2) Nope, there's more demand for that feature than demand for its removal. Date URL should work, though, but you have localized characters in your dates so it probably causes issues. Did you edit the dates directly in the metabox?

**Comment by CaerCam** [comment]
Closed due to inactivity, reopen if needed.
