### ISSUE TITLE
Default moviegrid

### ISSUE THREAD

**Issue by stargatehome** [wpmovielibrary/wpmovielibrary#207]
Hey Charlie,

the default site for the moviegrid has some problems. I don't have an option-menu for sorting, but that is there normally. Weird. 

See the picture.

![unbenannt](https://cloud.githubusercontent.com/assets/9327486/5671879/d3e0b708-978b-11e4-8807-6214d5e8ee33.JPG)

Mario

**Comment by CaerCam** [comment]
Try changing line 113 in `public/class-wpmoly-grid.php` from:

`
$content = self::render_template( 'movies/grid/menu.php', $attributes );`

To:

`
$content = self::render_template( 'movies/grid/menu.php', $attributes, $require = 'always' );`

Does that fix it?

**Comment by stargatehome** [comment]
Think it works now. See the picture: 
![unbenannt](https://cloud.githubusercontent.com/assets/9327486/5691037/79fc7e2e-98b3-11e4-8ae8-115a3a9b8bfa.JPG)
Is anything missing? :)

**Comment by CaerCam** [comment]
Nope, doesn't seem you are :)
