### ISSUE TITLE
Better collections handling

### ISSUE THREAD

**Issue by CaerCam** [wpmovielibrary/wpmovielibrary#208]
It could be nice to have a way to use collections instead of categories in themes. Most themes have a post meta box like "Poster by {author} on {date} in {categories}", but some themes don't test for the presence of categories on custom post types, resulting in empty string, and some that do some test won't show nonexistent categories when we would want to show collections, so I'm just throwing the idea to find a nice workaround to this, if any.

**Comment by lesurfeur** [comment]
Pour moi ce qui se rapprocherait le plus, se serait d'afficher le(s) genre(s) à la place de la catégorie dans ce cas, non !

**Comment by CaerCam** [comment]
Techniquement, dans la logique WordPress, les collections sont des catégories tandis que les genres sont des mots-clés (les collections sont hiérarchisables, les acteurs non), d'où l'idée de base. Cela dit ça ne serait de toute façon pas activé par défaut, et donc personnalisable ; on peut tout-à-fait imaginer une option pour choisir la taxonomie à utiliser :)

**Comment by CaerCam** [comment]
Closing as invalid: this should be handled by the theme, not the plugin. Too much complications.
