### ISSUE TITLE
Only want to have the post-content

### ISSUE THREAD

**Issue by stargatehome** [wpmovielibrary/wpmovielibrary#209]
Hey Charlie,

I have a little problem by using your plugin. I'm coding a different template for using the plugin but by showing the post-content it also shows the rating of the film in the right corner (see the picture). I want to have it on a different place. Could you add a option for disable it?

Thanks,
Mario

![unbenannt](https://cloud.githubusercontent.com/assets/9327486/5763220/f46c524a-9ce8-11e4-91c6-2a11d3b391a3.JPG)

**Comment by CaerCam** [comment]
There's one already, select "Nowhere" in the Settings panel, General > Details. That should do it :)

That being said, I think you want to take a look at the [`remove_filter()`](http://codex.wordpress.org/Function_Reference/remove_filter) function that could be usefull in such occasions ;)

**Comment by stargatehome** [comment]
Yeah you are right. Found the option. ;)
