### ISSUE TITLE
Double movie name

### ISSUE THREAD

**Issue by Fjellz** [wpmovielibrary/wpmovielibrary#210]
Is it a new thing that the movie name is writing before every headbox when press on a genre. Is it suppose to be like that? :)

![image](https://cloud.githubusercontent.com/assets/9780900/5842451/339bdc9a-a1a5-11e4-888f-a8efbfdefecd.png)

**Comment by CaerCam** [comment]
I guess so: it looks like a classic WordPress archive page, the first title (above hearbox) would be added by the theme just like regular posts/pages archives :-)

**Comment by CaerCam** [comment]
Confirmed: that's just the way the Sixteen theme displays posts. To avoid this you can try replacing your theme's `content-single.php` file by this edited one: https://gist.github.com/CaerCam/5a64a06cbec3e0b12ee4
