### ISSUE TITLE
New Headbox styles

### ISSUE THREAD

**Issue by CaerCam** [wpmovielibrary/wpmovielibrary#211]
cc @wpmovielibrary/testers 

Version 2.1.4 will introduce two new Headbox styles: Allociné and IMDb :)

![interstellar wordpress 4 1 2015-01-22 12-19-58](https://cloud.githubusercontent.com/assets/621662/5857729/461b3a6a-a24e-11e4-9c10-f0205bcdeaf5.png)

![interstellar wordpress 4 1 2015-01-22 11-39-52](https://cloud.githubusercontent.com/assets/621662/5857758/6a9ff1a0-a24e-11e4-9b93-eb98a4ce03fe.png)

**Comment by Ravavamouna** [comment]
Ah mais c'est énorme ! Et au niveau des shortcodes ça restera pareil ou
y'aura du changement ? En tout cas, bravo Charlie !

2015-01-22 15:51 GMT+01:00 Charlie Merland <notifications@github.com>:

**Comment by CaerCam** [comment]
Pas d'impact sur les shortcodes, ce sont simplement deux modes différents en alternative à l'en-tête actuel, et accessoirement une facilitation au développement et à l'intégration de nouveaux modes :) Je n'ai fait que ces deux là pour le moment parce que 1/ ça prend du temps et, surtout, 2/ je n'ai trouvé d'autres sites/exemples sympa à intégrer :P

Il faudrait voir, cela dit : il me semble que tu cherchais justement un moyen de personnaliser tes pages, et @lesurfeur développe de son côté un template perso, il y aura peut-être à l'avenir possibilité de les peaufiner et de les intégrer en supplément… To be continued !

**Comment by Ravavamouna** [comment]
Ok si tu cherches des exemples sympas y'a le script Movie Database que j'ai
vu sur CodeCanyon. La mise en page est pas mal si tu cherches des idées
http://codecanyon.net/item/movie-database-2/full_screen_preview/6002194
Ou l'Ultimate Move Database
http://codecanyon.net/item/mtdb-ultimate-movietv-database/full_screen_preview/6447206

Le 23 janvier 2015 09:27, Charlie Merland <notifications@github.com> a
écrit :

**Comment by CaerCam** [comment]
Bien vu, bookmarkés !

**Comment by lesurfeur** [comment]
Pas mal ces nouveautés.
Et si tu souhaites MTDB qui tourne avec le framework Laravel, je peux te le donner car je l'ai acheté lors de son lancement (et abandonné pour ton plugin wp) et j'ai donc toujours accès aux maj.

**Comment by lesurfeur** [comment]
Je viens de tester la 2.1.4 et c'est tout simplement magnifique.
Bon ma préférence va à la présentation d'allociné ;) 
Je pense que tu as prévu que l'on puisse mettre les photos/images des acteurs ?

**Comment by CaerCam** [comment]
Bien vu pour la marge, je vais tester sur différents thèmes pour voir.

Pour les photos des acteurs, absolument pas ! C'est pour ça que c'est toujours expérimental : les acteurs sont justes des taxonomies, ce serait un peu trop bordélique d'y associer des images et surtout ça compliquerait les choses quand l'extensions People sera en service, c'est-à-dire quand la version 2.2 sera bouclée. À ce moment-là je modifierai la headbox pour qu'elle intègre correctement les photos. Mais il faudra que j'ajoute une notice dans le panneau de réglages pour que ce point soit bien clair, sinon effectivement ça risque de perturber les utilisateurs. Pour l'instant je laisse les Headboxes en expérimental pour avoir des retours d'usage et des suggestions d'améliorations et d'options :)

D'ailleurs, pas bête pour l'utilisation uniquement sur la page des films, c'est une headbox très volumineuse − comme celle d'IMDb d'ailleurs − donc ça éviterait de surcharger les archives.

**Comment by lesurfeur** [comment]
Ok ok
Que va faire cette extension "People" exactement ?
Je préconisai sur la page des films car effectivement c'est lourd sur les pages d'archives et a mon sens inutile comme sur le site d'ou est tiré le style.
Pour les retours, je vais ouvrir un sujet.

**Comment by Ravavamouna** [comment]
Ah c'est intéressant que tu le précises. Je pensais qu'il y aurait
effectivement un moyen de mettre les photo des acteurs. J'ai hâte de
découvrir cette fameuse extension "People" en tout cas.

Le 22 février 2015 11:49, Charlie Merland <notifications@github.com> a
écrit :

**Comment by CaerCam** [comment]
Je ferai un topo détaillé sur l'extension People dans le repo kivabien, mais en gros elle permettra de gérer, en sus des fiches de films, des fiches pour chaque personne d'un film, technicien ou acteur. Elle utilise un nouveau custom post type avec un lot de métadonnées (biographie, date de naissance, etc) et la filmographie de la personne, qui pourra être croisée avec la liste de films de la médiathèque où il apparaît. On pourra aussi évidemment ajouter des photos.

Pour le moment le développement est en pause il reposera en grande partie sur la réécriture de la partie interactive du plugin (cf #), mais à terme il sera possible de créer les fiches acteurs en même temps que les films, voire d'importer des films depuis la fiche du personnage. Il y a pleins de possibilités :-)

**Comment by lesurfeur** [comment]
Ok good.J'ai hate de voir ce pluin en fonction sans tomber dans l'excès de tmdb sus cité plus haut ;)
