### ISSUE TITLE
Translating "adult"

### ISSUE THREAD

**Issue by stargatehome** [wpmovielibrary/wpmovielibrary#213]
Hey Charlie, 

I have a little problem with translating the "adult"-feature, because in German there doesn't exist a word for adult in this way we use something like "allowed for youth" so we would have the oppsite answer there (in case of yes, I wanna have no). If you know what I mean. Could you make an extra point for that in the translation?

![unbenannt](https://cloud.githubusercontent.com/assets/9327486/5891239/e9fffd18-a489-11e4-874e-5f270f488784.JPG)

Cheers, 
Mario

**Comment by CaerCam** [comment]
I don't see how it would possible, actually, at least not from a translation-only point of view: there are two completely separate parts ("Adult" and "Yes/No") so there's not really a way to change the yes/no logic from the translation part. But I've a glimpse of a fix that could work by using a filter, for the meta display if anything. I'll give it some thinking and get back to you.
