### ISSUE TITLE
Known problem/Question

### ISSUE THREAD

**Issue by stargatehome** [wpmovielibrary/wpmovielibrary#214]
Hey Charlie und Supporters,

I know we've talket about it but I am still to bad to handle this: I want to show a text-message if there wasn't picked a trailer or images. Could you provide me working code? :) At the moment I use the shortcodes for creating a custom theme for the library (I know that isn't that good).

![unbenannt](https://cloud.githubusercontent.com/assets/9327486/5891284/a9b300e0-a48c-11e4-8fa2-9bc434bfee07.JPG)

Cheers,
Mario

**Comment by CaerCam** [comment]
I've had an idea for showing a custom message if a Shortcode returns an empty result, I'll see to implement it.

If you weren't using Shortcodes, you could always check for an empty string:

	$director = wpmoly_get_movie_meta( get_the_ID(), 'director' );
	if ( '' == $director )
		echo 'No director could be found!';

**Comment by stargatehome** [comment]
Would be great! Cause I used a shortcode of my theme I cannot use "real coding" in this shortcode. (It's already shortcode-ception o.O) 

As you can see:
```php
$trailer =     '[movie_trailer id="the_ID();"]';

echo do_shortcode( '[tabs style="nav-tabs"]
                                  [tab title="Videos"]' .  $trailer . '[/tab]
                                  [/tabs]');
```

Have really no idea how to add your solution...  :/

**Comment by CaerCam** [comment]
Your first line is buggy, you're risking errors by using `the_ID()` inside a variable declaration. Use `$var = 'blah_' . get_the_ID() . '_blah';` instead. That should do it:

```php
$trailer = do_shortcode( '[movie_trailer id="' . get_the_ID() . '"]' );
if ( '' == $trailer )
	echo 'No trailer could be found!'
else
	echo do_shortcode( '[tabs style="nav-tabs"]
                                  [tab title="Videos"]' .  $trailer . '[/tab]
                                  [/tabs]');
```

**Comment by stargatehome** [comment]
Great, great, great, awesome, fantastic! :D It works. ;)

**Comment by stargatehome** [comment]
One last problem... :D Sorry for disruptions. :/ 

I have more tabs in the nav-tabs, so I want to have something like this (hope that is possible ;)). I'm really not that good at coding (unfortunately). But it try my best. And again thanks for your help. :)

```php
$trailer = do_shortcode( '[movie_trailer id="' . get_the_ID() . '"]' );

echo do_shortcode('[tabs style="nav-tabs"]' .
					if ( '' == $trailer )
						echo 'No trailer could be found!';
					else
						echo do_shortcode( '[tab title="Videos"]' .  $trailer . '[/tab]');
                                       .  '[/tabs]');
```

**Comment by CaerCam** [comment]
Don't worry, it all come with practice :) You don't need to echo everything right on, in your case you may as well use a variable that you will echo when you're done adding stuff. Try this:

```php
// Get the Shortcode output
$trailer = do_shortcode( '[movie_trailer id="' . get_the_ID() . '"]' );
// If output is empty, replace it with a message
if ( '' == $trailer )
	$trailer = 'No trailer could be found!';

// Other shortcode example
$title = do_shortcode( '[movie_title id="' . get_the_ID() . '"]' );

// Tabs
$tabs = '[tabs style="nav-tabs"][tab title="Videos"]' . $trailer .  '[/tab][tab title="Title"]' . $title .  '[/tab][/tabs]');
echo do_shortcode( $tabs );
```

That's cleaner code and technique :)

**Comment by stargatehome** [comment]
Thanks again man! I sat there for hours for a solution. :) Great!
