### ISSUE TITLE
title-problem

### ISSUE THREAD

**Issue by stargatehome** [wpmovielibrary/wpmovielibrary#215]
Hey Charlie,

I have a little problem with the title in the browser. Normally there are whitespaces, between the words, but only at the default movie-archives page there aren't none. Ideas?

![unbenannt](https://cloud.githubusercontent.com/assets/9327486/5891592/5bccddde-a49f-11e4-8bce-2450e9e7a385.JPG)

(PS: I always have a picture. :))

Cheers,
Mario

**Comment by lesurfeur** [comment]
Hi,
No problem with Firefox.
Movie page :
![capture1](https://cloud.githubusercontent.com/assets/5854465/5892117/9fb0ed28-a4b4-11e4-919c-20098bc4e220.PNG)
Archive Page
![capture2](https://cloud.githubusercontent.com/assets/5854465/5892118/a6f28e20-a4b4-11e4-85a2-976aff860b15.PNG)

**Comment by CaerCam** [comment]
I'll take a look, this probably comes from the separator used in the `wp_title` filter, generally something like ` | `, but the presence (or absence) of spaces can be a consequence of a conflict with other themes or plugins… I'll see if I can find a way to make it work correctly in most cases.
