### ISSUE TITLE
movie-title in widget

### ISSUE THREAD

**Issue by stargatehome** [wpmovielibrary/wpmovielibrary#216]
Hey Charlie,

I think the picture speaks for itself. :)

![unbenannt](https://cloud.githubusercontent.com/assets/9327486/5892609/0f464d34-a4c6-11e4-9ebc-f599d44f0d5b.JPG)

Would be nice to have an option for default length of the title.

Cheers,
Mario

**Comment by CaerCam** [comment]
Maybe a bit too much for this, as I recently discovered and applied a [nice way](https://github.com/wpmovielibrary/wpmovielibrary/issues/196#issuecomment-68287074) to handle this visual inelegance :)
