### ISSUE TITLE
Cant deactivate movie library plugin

### ISSUE THREAD

**Issue by kutluhanaykut** [wpmovielibrary/wpmovielibrary#218]
For the grid plugin i needed to deactivate/reactivate the main plugin but it gives 

Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 79 bytes) in /home/benzer/public_html/wp-includes/wp-db.php on line 1981

Any ideas...

**Comment by CaerCam** [comment]
I've add some similar report, but I can't really know what's causing this, having never encountered such behavior in any of my installs…

By the way, are you referring to [this plugin](https://github.com/wpmovielibrary/wpmovielibrary-movie-grid)? If so quit using it, is completely useless now (it was only a test plugin before the grid became part of the main plugin).

**Comment by kutluhanaykut** [comment]
Oh Yeah that was the plugin.. OK I am quitting from that.. Thx for the info.. 

About the bug.. 
I have approx. 1600 movies in database is deactivating tries to do huge process about the database that might couse the problem.. 

And one last question what about the meta updater plugin is it also an old one.. And isthere a way to update whloe database meta data with a plugin that works as a cron job or st. like that. (I guess TMDB wont allow whole process of huge movie collections at once)

Thx.

**Comment by CaerCam** [comment]
No problem, I'll remove that obsolete repo to avoid further confusion.

As for the deactivation thing, depending on your settings the plugin can convert movies to posts or delete them completely; default is to conserve movies when deactivating, convert when uninstalling. Maybe that could explain?

And about the updater plugin − which is experimental, too − no, at the moment there isn't such thing as a CRON to periodically update movies, though it can be an interesting idea.

**Comment by kutluhanaykut** [comment]
Actually it might be a useful thing after a while.
When the keywords added to script I actually will need to re-fecth all the movie data to add the keyword to existing movies..

**Comment by CaerCam** [comment]
Indeed. It will have to wait for version 2.2 though, as this version is going to implement more possibilities for plugins to hook and interact with the main plugin.
