### ISSUE TITLE
Erro em class "public/class-wpmoly-movies.php" linha 566

### ISSUE THREAD

**Issue by RodriguesCosta** [wpmovielibrary/wpmovielibrary#219]
Hello I found an error at line 566 of file "public/class-wpmoly-movies.php" because the options are set in both the line of the function as the low, I have here in my fix.

I apologize for the mistakes of their language I do not speak English fluently, I used the google translator.

and one more thing congratulations for the great plugin.

**Comment by CaerCam** [comment]
Wow, nice one! This is what happens when you copy-paste;functions without thinking... Thanks :-)
