### ISSUE TITLE
FORCE HTTPS in the header

### ISSUE THREAD

**Issue by kutluhanaykut** [wpmovielibrary/wpmovielibrary#220]
When i look at the title of my pages it always adds "Force HTTPS" Before the movie name.. ?!?

**Comment by kutluhanaykut** [comment]
Sorry i wrote it wrong

it appears only when i seacrh something.. 
Like http://benzerfilmler.com/?s=god+father
RESULT IS
<title>Https zorla god father - Moviesalike</title>
WHERE
"Https zorla" means "Https force" in Turkish...


And "500" is ireelevant it was there because i searched the word "500".
It only adds "Force HTTPS" in the header when i seacrh st.

**Comment by CaerCam** [comment]
Could it be related to your API settings? Did you try switching HTTPS/HTTP in the plugin's settings panel?

**Comment by kutluhanaykut** [comment]
I did now.. Still the same.. strange

**Comment by kutluhanaykut** [comment]
I was using search everything plugin i disabled it.. But No success
I wasn't using my Api Key I entered it now but still.. No success

**Comment by kutluhanaykut** [comment]
Found the issue but dont know how to resolve..
I was using YOAST SEO plugin when i disabled it everything seems fine.
To recheck i enabled it problem occured again

There might be a setting in YOAST SEO plugin.. 
I will look at it later.. If i find it i will write it here..

**Comment by CaerCam** [comment]
Ha, that was my next question, I noticed the only "https" occurrences in the page's source code wast YAST SEO. Not sure why this is happening, though.
