### ISSUE TITLE
Function Poster choose does not work in multisite

### ISSUE THREAD

**Issue by RodriguesCosta** [wpmovielibrary/wpmovielibrary#221]
Hello again, I noticed something else when I use the plugin in multi site the option to choose the movie poster appears that not being in the main network site the option appears, tried to find the code to resolve the situation but to no avail.

I apologize for the mistakes of their language I do not speak English fluently, I used the google translator.

and one more thing congratulations for the great plugin.

**Comment by CaerCam** [comment]
Hi Rodrigues,

Not sure I understand you correctly, I'm using the plugin on a couple of multisite WordPress installations and I can't find any issue with the Poster part. Could you detail more what's happening?

**Comment by RodriguesCosta** [comment]
I'm sorry my mistake, the problem was my theme that did not support thumbnails, apologize for having reported an error that does not exist. thank you for the attention you are really doing a great job with this plugin.

**Comment by CaerCam** [comment]
No problem ;) What's that theme, by the way? Always to know which ones can be trouble to use with the plugin!

**Comment by RodriguesCosta** [comment]
I'm actually developing a theme for this plugin, oh just committing this error not add "add_theme_support('post-thumbnails');" when completed intend to provide the same for free.
