### ISSUE TITLE
title problem

### ISSUE THREAD

**Issue by stargatehome** [wpmovielibrary/wpmovielibrary#223]
Hey Charlie,

by hovering over the date there shouldn't be written that: 6. Mai 2003 (6. Mai 2003). Better something like: "More Movies with the release date 6. Mai 2003".

By hovering over a name of an actor should be the name.

![unbenannt](https://cloud.githubusercontent.com/assets/9327486/6068688/71efa6ea-ad7e-11e4-96b3-a565a306c33d.JPG)

Cheers,
Mario

**Comment by CaerCam** [comment]
Makes sense. Scheduled for 2.1.4 :)

**Comment by CaerCam** [comment]
Done, now there are friendlier link titles: "More movies for Brad Pitt", "More movies for Christopher Nolan", "More movies released on august 2014", "More movies produced by Universal", "More movies from France", and so on :)
