### ISSUE TITLE
director bug

### ISSUE THREAD

**Issue by stargatehome** [wpmovielibrary/wpmovielibrary#224]
Hey Charlie,

if a movie has more than one director (as you can see in this picture):

![asdf](https://cloud.githubusercontent.com/assets/9327486/6092792/6efca2a4-aeef-11e4-9b47-3909385de378.JPG)

There are not created two collections (as you can see here):

![unbenannt](https://cloud.githubusercontent.com/assets/9327486/6092790/5e66d34c-aeef-11e4-9839-c583bb67c8b9.JPG)

Cheers, 
Mario

**Comment by stargatehome** [comment]
Still in 2.1.4.1 (actual version)

**Comment by CaerCam** [comment]
Actually I still can not reproduce this. Works perfectly everywhere I tested :-/

**Comment by stargatehome** [comment]
I'm very confussed about that. Because (that movie was imported with the acutal version) it uses the third director in that case again.
![unbenannt](https://cloud.githubusercontent.com/assets/9327486/7110800/72b36bb2-e1b7-11e4-837d-45cb088bae74.JPG)

**Comment by stargatehome** [comment]
Maybe the issue is because of the name? Or because that person exist as both: Actor and director?

**Comment by CaerCam** [comment]
Ha, I think you may have a very good clue here! I'll browse the doc, run some tests and get back.

**Comment by CaerCam** [comment]
Do you have a live site where you could set up a temporary account so I can run some tests on this?

**Comment by stargatehome** [comment]
Sure send you via PM. :)

**Comment by stargatehome** [comment]
Or better per Mail. :D

**Comment by CaerCam** [comment]
Ok, temporarily fixed on your site: the only quick and effective way to add collection is to use JavaScript to simulate a manual "new collection" action by filling up the input field and triggering a click, but it requires a delay to make sure the different queries don't crash together. That delay is set to 1000 seconds (`assets/js/admin/wpmoly-editor-meta.js`, line 287) and that seemed to be the problem with your site; increasing the delay to 2000 fixed things up.

I'll try to find a simple and clean way to solve this, without recoding the complete tax-adding process…
