### ISSUE TITLE
movie grid improvement

### ISSUE THREAD

**Issue by stargatehome** [wpmovielibrary/wpmovielibrary#225]
Hey Charlie,

at the moment you can only sort movies by name. (Have I missed an option? :D)

![unbenannt](https://cloud.githubusercontent.com/assets/9327486/6092800/aabb83be-aeef-11e4-8090-c9130131f3fb.JPG)

There should be the abillity to sort after "local release date", "release date", "rating" and "genre". Also a combination should be available.

Hope that will help.

Cheers,
Mario

**Comment by zack06007** [comment]
Hello, 
I'm interessed to have rating, genre, or date... ;) 
Good week end

**Comment by CaerCam** [comment]
Added sorting by all mentioned values minus genre. That's experimental still and needs to be activated in the settings panel, but it should work. Don't forget to reload permalinks!
