### ISSUE TITLE
new movie grids

### ISSUE THREAD

**Issue by stargatehome** [wpmovielibrary/wpmovielibrary#226]
Hey Charlie,

what do you think about new movie grids? For example: I want have a movie grid for the actual playing movies in cinema, one for upcoming movies and another one for the best ratest movies.

Cheers,
Mario

**Comment by CaerCam** [comment]
Not sure you mean by "new": you can already have an unlimited number of grids using the Shortcode, the only limitation is the content control; but as version 2.1.4 will support collections/actors/genres/meta/details that's a big number of grids already… Could you explain more what you have in mind?

**Comment by stargatehome** [comment]
I think that would be something you told, but some special options. I thought about the following new options: showing upcoming movies (will be released within 3 months from today), cinema-movies (in cinema (movies released today and since 3 months ago)) and the best ratest movies showing movies sortable by rating.

Hope you understand me. :)

Cheers, Mario

**Comment by CaerCam** [comment]
Ok, misleading title then: new grid options :-) 

I'll think about a more generic way to handle the upcoming movies, it could be done with the release date metadata, possibly by using a couple like `meta=release_date" value="now-3 months"`...

**Comment by stargatehome** [comment]
Great. :)
