### ISSUE TITLE
poster shortcode improvement

### ISSUE THREAD

**Issue by stargatehome** [wpmovielibrary/wpmovielibrary#227]
Hey Charlie,

would be nice to override the link of the poster printing by the shortcode for example by clicking on the poster i want to transfer the user to youtube. The shortcode would be [movie_poster link="http://youtube.com"].

Cheers,
Mario

**Comment by CaerCam** [comment]
Not sure that's a good idea, mainly because I don't see many cases where it could be useful, it looks more like a templating need. What use would you make of it exactly?

**Comment by stargatehome** [comment]
Thought about giving a new link by clicking on the poster (let me have a look at my template, maybe I can overwrite the acutal link, because if you're clicking on the poster it leads to the picture). :) Will be back soon.
