### ISSUE TITLE
disable summary-import

### ISSUE THREAD

**Issue by stargatehome** [wpmovielibrary/wpmovielibrary#229]
Hey Charlie,

it would be nice to have an option to disable the automatical summary-import (because normally you write your own ;)). Think about it. :)

Cheers,
Mario

**Comment by CaerCam** [comment]
For clarification, do you mean the overview imported from TMDb, as in "have an option to chose __not__ to import the overview at all", or the Post Excerpt that is automatically filled with the imported overview?

**Comment by stargatehome** [comment]
I mean the overview imported from TMDb. :)

**Comment by CaerCam** [comment]
Ok. I'll save that for version 2.2 the editor (and importer) will offer the possibility to change the settings temporarily before importing movies, for instance you'll be able to chose not to set poster as featured image for the current movie without needing to edit the plugin's settings. I'll add a way to chose which meta to import or rather not import.
