### ISSUE TITLE
more options for movie grid

### ISSUE THREAD

**Issue by stargatehome** [wpmovielibrary/wpmovielibrary#230]
Hey Charlie,

what about enabeling also the number-rating in the movie-grid?
![d](https://cloud.githubusercontent.com/assets/9327486/6092998/3c1b1f3e-aef7-11e4-9885-ba1a734e913b.JPG)

Cheers,
Mario

**Comment by CaerCam** [comment]
There already was a `rating` parameter supported by the `[movie_grid]` shortcode, but it was not implemented yet; I added it this afternoon, please test with the latest version :-) 

The doc is outdated, I'll try to find time to update it.
