### ISSUE TITLE
title shortcode

### ISSUE THREAD

**Issue by stargatehome** [wpmovielibrary/wpmovielibrary#231]
Hey Charlie,

I would like to have an option using the [movie_title]-shortcode for the max-length of the title: For example the shortcode: [movie_title length="13"] should return: "Matrix Rel..." and show the whole title by hovering over it. 

Cheers,
Mario

**Comment by CaerCam** [comment]
Not a good idea I think, looks like you're taking the problem upside. I guess you're having trouble with long titles that mess up the design? If so, it's really client-side issue and should be dealt with CSS, there's a nice way to do it that you can see used in the grid for instance. If you have a link I'll provide a small code to handle that :)

**Comment by stargatehome** [comment]
At the moment I use only the shortcode for showing the title: [movie_title] and a custom css-class. Would be great if you have an idea. :)

**Comment by CaerCam** [comment]
`
.title {
text-overflow: ellipsis;
white-space: nowrap;
overflow: hidden;
}`

Should do it on your custom class :)
