### ISSUE TITLE
problem with the production companies

### ISSUE THREAD

**Issue by stargatehome** [wpmovielibrary/wpmovielibrary#233]
Hey Charlie,

the image speaks for itself. The Companies are imported to often and are not seprated trough the commas. 

Mario

![unbenannt](https://cloud.githubusercontent.com/assets/9327486/6199156/a7708d7e-b432-11e4-9ddf-50251d112c47.JPG)

**Comment by CaerCam** [comment]
Are you sure there's an import issue? Looks more like a bug with the way the meta are displayed, I fixed something like that today, see the latest version if it fixes it :-)
