### ISSUE TITLE
Use JavaScript/Backbone to control the grid

### ISSUE THREAD

**Issue by CaerCam** [wpmovielibrary/wpmovielibrary#234]
Grid is nice but limited on many points due to its use of permalinks and dependence on URLs. Making it fully controllable by JavaScript and Ajax will solve this completely and open the door to more features.

Not for soon, at least not before version 2.3 or 2.4, but still in project.

**Comment by CaerCam** [comment]
Ok. There's a problem with the way the grid works and it's getting on my nerve. I think I will just drop any interactive sorting feature for version 2.1.4 , meaning it will be − temporarily − impossible to alter the order of the grid from frontend (sorting by options or shortcode parameters shall remain). That's just causing to many issue. And on a second time, I'll rebuild the grid to use JavaScript for version 2.1.5 instead of 2.x (x>2).

That's a pain right now cause it means some time spent with a very limited grid, but it also means more features to come: really advanced sorting, infinite scroll, template changes withou reloading the page, and so. The magic of JavaScript.

Sorry about the wait on this guys. I should've thought this through months ago.

Ping @wpmovielibrary/testers, @lapinzed and @zocoloco

**Comment by lapinzed** [comment]
Ok @CaerCam , effectivement tu seras beaucoup plus souple avec javascript!  Et pour l'ordre de tri modifiable uniquement par les options dans un 1er temps, c'est franchement pas gênant.. 
Tu penses nous proposer dans combien de temps une beta à tester? 
Merci et bon courage!
