### ISSUE TITLE
movies_shortcode

### ISSUE THREAD

**Issue by stargatehome** [wpmovielibrary/wpmovielibrary#235]
Hey Charlie,

would be nice to have seperated div-classes in the movies_shortcode_view, like it has the grid. Because it's easier to style. :)

Cheers,
Mario

**Comment by CaerCam** [comment]
It already has, kind of:


	├─ .wpmoly.shortcode.movies
	    ├─ .wpmoly.shortcode.movie
	        ├─ .wpmoly.shortcode.poster
	        ├─ .wpmoly.shortcode.link
	        ├─ .wpmoly.shortcode.meta
	        ├─ .wpmoly.shortcode.details
	        ├─ .wpmoly.shortcode.[…]
	    └── […]
