### ISSUE TITLE
Améliorations Nouvelle Headbox styles

### ISSUE THREAD

**Issue by lesurfeur** [wpmovielibrary/wpmovielibrary#236]
##### Allociné
Améliorations : 
- 1 - Doublons du Titre et de l'image.
![capture](https://cloud.githubusercontent.com/assets/5854465/6319256/9d1c2052-bab5-11e4-8a60-aa006cca9dff.PNG)

- 2 - Pouvoir choisir les métas que l'on souhaite faire apparaitre.
- 3 - Pouvoir choisir les détails que l'on souhaite faire apparaitre.
- 4 - Utlisation que sur la page film et non archive ou en option. https://github.com/wpmovielibrary/wpmovielibrary/issues/211#issuecomment-75364734
- 5 - CSS du menu :  https://github.com/wpmovielibrary/wpmovielibrary/issues/211#issuecomment-75364734

**Comment by CaerCam** [comment]
1. Ok pour le titre, pour l'affiche c'est plus du ressort du thème : le plugin ne peut pas empêcher le thème d'afficher l'image à la une, et la headbox fait vide sans.
2. Application des réglages, oui, un oubli.
3. Idem

**Comment by lesurfeur** [comment]
Pour la 1, je m'attendais à cette réponse ;) mais comme la plupart des styles l'utilse (cg le thème officiel) il serait peut être et si possible bon de la mettre à la place de l'affiche dans la headbox, non ? Je sais que c'est à double tranchant mais au vu de l'utilisation des archives "classique" il faut l'activer me semble t'il, alors why not.

**Comment by CaerCam** [comment]
Je ne dois pas être réveillé, parce que j'ai rien compris :D

Je me demande s'il ne vaudrait pas mieux laisser au thème le soin de masquer ce qu'il veut ou ne veut pas voir, en fait ; ajouter une option pour masquer le titre est parfaitement envisageable, mais ça parait un peu exagéré : d'un côté on a une ligne de CSS à ajouter au thème, de l'autre une option à ajouter et implémenter, ce qui représente plusieurs blocs de code supplémentaires dans différents fichiers, du temps de traitement, et une des requêtes à la base de données… Il faudrait peut-être sérieusement envisager la possibilité d'ajouter ses propres CSS directement via le panneau de réglages. Ça fournirait une solution parfaite à ce genre de problèmes sans pour autant surcharger le plugin d'options qui empiètent sur le thème ou la gestion. Parce que l'air de rien, avoir le titre du film en haut de la Headbox, ça a son utilité dès l'instant où ladite Headbox n'est pas affichée en haut de la page − on peut l'afficher en bas − ou si le titre du Post n'est pas le titre du film… C'est fréquent sur un certain nombre de sites que j'ai vu utilisant le plugin.

Sinon, je suis en train de voir pour le point 4 : en soi ce n'est pas compliqué, la question est, par quoi remplacer la Headbox ?

**Comment by zack06007** [comment]
Carrément d'accord 
Y a tellement a faire qu'il faut pas se compliquer la vie quand chacun d'entre nous peux améliorer son thème !!! Merci a toi

Envoyé de mon iPhone

**Comment by lesurfeur** [comment]
Je suis bien d'accord mais je parler d'un utilisateur lambda qui ne sait ou ne souhaite pas mettre les mains dans le css. Après pour moi...
L'utilisateur du plugin souhaitera peut être avoir le moyen de gérer au mieux l'affichage via ce genre d'apparence puisqu'il s'agit bien de cela avec l'utilisation de ces modules "headbox". Comme par exemple l'affichage du titre dans celle ci en fonction du placement de la headbox en haut ou en bas.
Ce n'était qu'une suggestion ;)

**Comment by CaerCam** [comment]
J'entends bien, c'est vrai que j'ai tendance à penser que ce type de détails tombe dans le cas du support ; peu d'utilisateurs posent ce genre de demande et, le cas échéant, il est souvent plus facile de leur fournir une ligne de CSS à copier-coller que d'ajouter une option. Le soucis est surtout la cohérence : ajouter une option pour masquer le titre implique, logiquement, de le faire pour les autres styles, ou pour d'autres parties du plugin ou des Headbox, ce qui au final génère beaucoup de code supplémentaire pour une utilité limitée sur l'ensemble des utilisateurs.

Par contre, excellente idée que d'afficher le titre si la Headbox Allociné est disposée à la fin du post, et de le masquer si elle est disposée au début. Ça pour le coup, ça mérite peut-être même d'être appliqué par défaut, en CSS.

Je reviens sur le point n°4 : par quoi remplacer la Headbox Allociné (ou IMDb, même problème) dans les archives ? Il n'y pas de moyen de calquer l'affichage des archives du thème, donc il faut un contenu simple mais efficace pour remplacer la Headbox… Peut-être revenir à la Headbox principale ? Ce serait le plus élégant visuellement, mais ça manque de cohérence…

**Comment by CaerCam** [comment]
→ cf0e423b0ecc1349c8fd9bb45e6ae0b2710c772a

**Comment by lesurfeur** [comment]
Point 4 : Afficher la page comme elle était précédemment --> Archive
Mais si j'ai bien compris ce n'est pas possible !

D'autre part, j'ai constaté que si l'on ne souhaite pas utiliser de headbox ce n'est pas possible.
Et une option a disparue du menu Général --> Films --> Utiliser l'ancien affichage

**Comment by CaerCam** [comment]
Pas possible non : il n'est pas envisageable pour un plugin de copier le fonctionnement d'un thème, à cause de la variété de thèmes disponibles et des différences de fonctionnement :/

Pour l'option manquante, en fait oui et non, elle est passée dans Apparence > En-tête > Activer l'en-tête. C'était plus cohérent vue l'ampleur que prend cette partie. Je viens de corriger l'implémentation de cette option, désormais si l'en-tête est désactivé c'est l'ancien affichage qui prend le relai. Le bug #237 est une conséquence de cet oubli.
