### ISSUE TITLE
Plus d'affichage des films sous forme de liste de titres avec la version en date du 28/02/15

### ISSUE THREAD

**Issue by lesurfeur** [wpmovielibrary/wpmovielibrary#237]
Bonjour,
J'utilise le système de grille sur une page avec le shortcode [movie_grid].
Lorsque je veux afficher les films sous forme de liste de titres, rien n'apparait. Les deux autres affichages fonctionnent quand à eux.
Lien de la page : h ttp://wpmovielibrary/liste-des-films/archives/6:6/title/DESC/
![capture](https://cloud.githubusercontent.com/assets/5854465/6425800/fd52ad4e-bf3b-11e4-83dc-41ee2dd4911d.PNG)

**Comment by CaerCam** [comment]
Ok, je vais regarder ça. Tu utilises quelle Headbox ?

**Comment by lesurfeur** [comment]
Ca le fait quelques soit la headbox choisie.

**Comment by CaerCam** [comment]
Corrigé, conséquence de #236.

**Comment by lesurfeur** [comment]
Ne fonctionne toujours pas ;)

**Comment by CaerCam** [comment]
Pas de solution pour l'instant puisque ça fonctionne parfaitement sur toutes mes versions de test, peu importe les réglages : changement de langue, activation/désactivation de la headbox avec tous les styles… Rien à faire, les archives s'affichent correctement.

Je vais réfléchir à un moyen d'obtenir des informations de débuggage (cf https://github.com/wpmovielibrary/wpmovielibrary/issues/243#issuecomment-80983316) pour régler ce genre de problèmes.

C'est vraiment une saloperie cette grille, y a rien qui marche. Vivement #234 :P

**Comment by CaerCam** [comment]
J'ai ajouté une option de debug dans les réglages, Advanced > Debug Mode. Ça dumpe les paramètres de la grille pour voir ce qui peut clocher.

Accessoirement, je vais revoir drastiquement les modifications interactives de la grille (cf. https://github.com/wpmovielibrary/wpmovielibrary/issues/234#issuecomment-81590279), ça devrait trop bordélique à gérer, la gestion du classement par URL pose de gros problèmes. On va tout passer en JavaScript avec une gestion de l'affichage via Backbone et un chargement de la grille en AJAX. Ça permettra des modifs interactives bien plus étendues, y compris pour les modes d'affichage, et accessoirement des fonctionnalités sympa comme le chargement par défilement (infinite scroll).

**Comment by lesurfeur** [comment]
Ok on va passienter ;)
On avait déjà eu ce problème et que tu avais rectifié mais je trouve plus le sujet dans les issues...
Car la j'ai même fait une instalation toute fraiche et idem quelques soit le style, réglage ect...

**Comment by lesurfeur** [comment]
Mea culpa, je me souvenais plus que j'avais créé un dossier wpmovielibrary dans mes thèmes qui modifier certaines choses dont la grille :(

**Comment by CaerCam** [comment]
Oui, c'est la fameuse option qui a changé de nom, c'est devenu `headbox-enable`, plus cohérent :-)
