### ISSUE TITLE
Merci pour cette année passé avec wpmovielibrary...

### ISSUE THREAD

**Issue by lesurfeur** [wpmovielibrary/wpmovielibrary#238]
Juste pour dire que cela fait un an que je suis tombé sur ton plugin (https://github.com/wpmovielibrary/wpmovielibrary/issues/1#issue-28248238) et que depuis la version 1 beaucoup de chemin a été parcouru.
Je te remercie encore une fois pour : le plugin, ton implication et de nous offrir un support digne de ce nom.

Respectueusement,
lesurfeur.

**Comment by CaerCam** [comment]
Et merci à toi d'être là depuis le début ! L'implication dans le développement est aussi le reflet de l'implication des utilisateurs, et tu es le premier utilisateur historique :)

Effectivement du chemin a été fait depuis la première mouture, et ce n'est pas terminé, j'ai un gros paquet d'idées à concrétiser qui devraient nous garder occupés pendant un bon moment encore :sunglasses:

**Comment by CaerCam** [comment]
(Je ne sais pas pourquoi j'ai mis des labels et des milestones, moi, j'ai du confondre avec un autre fil…)
