### ISSUE TITLE
Shortcode Problem

### ISSUE THREAD

**Issue by sabitkamera** [wpmovielibrary/wpmovielibrary#241]
Hi! First of all, this plugin is the best.

I have a problem with use shortcode.
 I'm try this shortcode in my post "[movie title="Birdman" poster="full" meta="director|runtime|release_date|genres|actors|overview" details="rating|media"]" but after publish the post, page don't show.
Movie metadata shortcodes works. But general shortcodes does'nt works.
I'm sorry for my fuckin' English :ghost: 

Wordpress version: 4.1.1
Permalink structure: /%postname%/
Active Theme: Tracks 1.33.1

Active Plugins:
Akismet 3.0.4
Google Analytics 1.0.6
Google XML Sitemaps 4.0.8
WordPress.com’s Jetpack 3.3.2
WordPress Importer 0.6.1
WPMovieLibrary 2.1.3.1

**Comment by CaerCam** [comment]
Hi there Andaç,

I just tested using your theme (Tracks) and it seems to work correctly. What version of PHP are you using? Pages not showing/showing blank generally means PHP error. Do you have a link of a page that shows the issue?

**Comment by sabitkamera** [comment]
Hi.
PHP Version is 5.3.29
I'm created new test page and use this shortcode.
[movie title="Birdman" poster="full" meta="director|runtime|release_date|genres|actors|overview" details="rating|media"]

Test page link: http://sabitkamera.com/test/

**Comment by sabitkamera** [comment]
I'm a stupid. Now i changed the settings on wp-config "define('WP_DEBUG', true);.
And the test page show this problem:

Fatal error: Call to private method WPMOLY_Shortcodes::prepare_movies() from context '' in /home/sabitkam/public_html/wp-content/plugins/wpmovielibrary/public/class-wpmoly-shortcodes.php on line 258

**Comment by CaerCam** [comment]
Looks like an issue with PHP 5.3. That version is completely outdated but still used by some hosts so I sometimes have to make the code compliant… Try updating to PHP 5.4 if you can, and in any case try changing line 818 of file `public/class-wpmoly-shortcodes.php` from:

`
private static function prepare_movies( $query, $atts ) {`

To:

`
protected static function prepare_movies( $query, $atts ) {`

**Comment by sabitkamera** [comment]
Thank you. After uptade php version to 5.4 this problem solved. I have another question. How can i do 3 or 4 movie headbox in one post. I want to make a movie list.

**Comment by CaerCam** [comment]
Hum, there's no direct way to do that, but you could probably achieve something likely by using a grid with `menu` disabled and `view` to archives. Put your movies in a collection and use that collection for the grid. For instance:

`[movie_grid collection="You collection" menu="false" view="archives"]`
