### ISSUE TITLE
Différents modes de tri dans la page d'archives

### ISSUE THREAD

**Issue by lapinzed** [wpmovielibrary/wpmovielibrary#242]
Salut,
Sur la page des archives, les différents modes de tri ne fonctionnent pas. 
Déjà en arrivant sur la page, les films sont classés de manière aléatoir (ou autre mais pas ce que j'ai demandé en tous cas!)
En cliquant sur les petites flèches de tri, quelque soit le choix il n'en ressort aucun résultat.
Merci encore pour ton taf et ton implication dans ce plugin vraiment au top!
v2.1.4
Lapinzed

**Comment by CaerCam** [comment]
Possible problème de permaliens ? Le classement par défaut est l'ordre alphabétique (par titre, donc), ça ne devrait pas être aléatoire.

**Comment by lapinzed** [comment]
Effectivement c'est par ordre alphabétique, je devais être fatigué hier soir désolé.. Mais de toute façon dans les options j'ai mis classement par date et non alphabétique

**Comment by CaerCam** [comment]
Les permaliens ont été rechargés ?

**Comment by zack06007** [comment]
Pour la grid (archives), j'ai la fonction ''archiver sous forme de liste de titres'' qui ne fonctionne pas non plus. Enfin j'ai bien des titres dans tous les sens mais rien de cliquable. Je suis en version WPML,  je n'utilise pas les thèmes IMDB ou allociné qui ne fonctionne pas avec mon thème parent de couleur noirs - de plus je suis assez content de ma présentation.

De plus la fonction ''archiver sous formes de listes étendues" ne peut pas etre déployé sur plusieurs colonnes? Car la liste semble bien vide sur une grande page - en 2, voir 3 colonnes ca serait juste magique! :dancer:

**Comment by CaerCam** [comment]
La grille est en plein chambardement, je suis en train de la passer sous Backbone (cf. #234) donc beaucoup de choses vont changer, que ça soit dans les méthodes de classement (actuellement tout est basé sur les URLs, ce qui est à la fois stupide et incroyablement bordélique), dans la navigation (infinite scroll, pagination sans rechargement) et dans l'affichage (basculement de la vue en grille à la vue en liste ou en liste étendue en un clic, sans rechargement de la page, donc avec conservation du classement). Bref, que du bon j'espère ;-)

**Comment by zack06007** [comment]
Ça c'est génial 
Y aura du boulot, entre le Moment ou l'idée est né et ce que ça va devenir ! J'ai hâte c'est top !1

Envoyé de mon iPhone

**Comment by zack06007** [comment]
Edit: sinon j'ai une idée suplémentaire: lorsqu'on va sur l'archive il serait peut etre bon d'afficher aléatoirmeent une lettre (A-H-U... etc) afin de dynamiser le site. En effet quand je clique sur archives on tombe toujours sur la même liste (celle du 0-1-2...), pensant que celle-ci ne bouge jamais. Pourtant elle grandit chaque jour, l'effet aléatoire permettrai au gens qui consultent l'archive de ne jamais voir la même affiche dès qu'ils entrent dedans. Après rien n'empeche qu'ils continuent ensuite à faire leur recherche avec l'index mis en place en haut. Enfin c'est une idée parmis tant d'autres.

**Comment by CaerCam** [comment]
Sur le principe ça me fait tiquer : ce n'est pas vraiment le but d'une page d'archive, non ? Quand je regarde des archives je m'attends à trouver les contenus que je veux classés logiquement, si c'est tout aléatoire je vais croire à une erreur…

Je comprends bien l'idée d'attrait, cela dit. Mais c'est à mon avis plus du ressort d'un outil à part, par exemple pour présenter les dernières entrées, quelques entrées populaires ou quelques entrées au hasard. Dans le cas de la page d'archive ce serait à mon avis plus pratique d'utiliser un Shortcode pour afficher une grille avant les archives, non ?

**Comment by lapinzed** [comment]
Je suis d'accord avec @CaerCam , il est plus adapté de l'implanter séparément. Mais d'un autre coté, quitte à avoir tous les mode de tri dans la page d'archive, tu peux laisser le choix à l'utilisateur d'avoir un mode aléatoire parmi les autres possibilités de classement, après tout c'est lui que ça regarde si il désir ce mode de classement.. Et puis ça évite à l'admin du site qui veut cette fonction de créer une autre page pour ça, en plus de la page d'archive.
La solution est peut être de laisser le choix des modes de tri proposés dans les options pour que chaque admin choisisse ceux qui l'intéresse?

**Comment by CaerCam** [comment]
C'est la meilleure façon, je pense, effectivement. À voir comment implémenter ça, on va déjà essayer d'avoir une grille qui fonctionne correctement :smile:

**Comment by zack06007** [comment]
C'est pas le classement que je voyais aléatoire mais juste l'affichage de la première page d'entrée.

Pas simple d'être clair: quand je clique sur Archive par défaut je vais sur la lettre 0-9.
Pourquoi pas tomber sur la lettre B, C ou J... Car de toute façon quand on cherche un film, c'est pas obligatoirement la page 0-9 qui nous interesse. C'est juste un moyen de dynamiser l'entrée dans les archives. Après c'est une idée totalement accessoire et sans utilité, tinquiète Charlie ;)
