### ISSUE TITLE
Who is the reviewer?

### ISSUE THREAD

**Issue by stargatehome** [wpmovielibrary/wpmovielibrary#246]
Hey Charlie,

it would be nice to add a WordPress-User as reviewer so that you can easily show him as the author of the ciritc (could be maybe done through WordPress, not quite sure).

Cheers,
Mario

**Comment by CaerCam** [comment]
More a WordPress concern indeed; movies are custom post types, so they have an author just like every other posts, that's probably that user you want to show. Displaying this is more theme- than plugin-related, though.

**Comment by zack06007** [comment]
Create a database that references all the authors based on a film title would be ideal - with a filter by country for language issues would be ideal... My dream for read you!

**Comment by CaerCam** [comment]
Yeah, sorry it's taking so long. If you followed a bit the development on version 2.2 you saw what that version will look like. Just imagine what will be possible with that kind of technology (Backbone) to interconnect reviewers ;-)
