### ISSUE TITLE
Adding a movie manually is to much work 

### ISSUE THREAD

**Issue by stargatehome** [wpmovielibrary/wpmovielibrary#247]
Hey Charlie,

I think we can optimze the "manual adding of a movie" to the databse not found in the TMDB. I have to add the director two times and also the actors:
![unbenannt](https://cloud.githubusercontent.com/assets/9327486/6771078/95f2056e-d0d4-11e4-87df-90c14ff18b5b.JPG)
Same problem with the genre. :)

Hope you have an idea of it. Could be a great improvement. 

Cheers,
Mario

**Comment by CaerCam** [comment]
No, I do understand the issue. I'll try to find a simple way to put this in version 2.1.4, but I'm still scheduling for version 2.2 in case it's too much trouble (since version 2.2 is a rewrite of the specific part -- the metabox -- I'll add this to it anyway).
