### ISSUE TITLE
Panneaux dans les entêtes

### ISSUE THREAD

**Issue by lapinzed** [wpmovielibrary/wpmovielibrary#249]
Version 2.1.5 dev : Les panneaux sont bien affichés mais ne mènent nul part lorsqu'on clique dessus

**Comment by CaerCam** [comment]
Normal, c'est une branche en plein développement ouverte ce matin, je n'ai même pas encore entamé cette partie (headbox) ;-) Les versions *-dev sont généralement bourrées de bugs, elles servent uniquement à développer des fonctionnalités qui seront à tester plus tard.

**Comment by lapinzed** [comment]
OK je vais attendre un peu avant de tester alors!

**Comment by CaerCam** [comment]
Pas de soucis ;-)
