### ISSUE TITLE
Importer et exporter vos réglages et films depuis un fichier, un texte ou une URL.

### ISSUE THREAD

**Issue by lesurfeur** [wpmovielibrary/wpmovielibrary#251]
Salut Charlie,
Que doit réellement faire cette option.
Car a part les réglages, elle n'exporte rien d'autre, n'est ce pas ?
Le "et films" est un peu trompeur.

**Comment by CaerCam** [comment]
Elle exporte/importe les réglages, oui. J'ai un temps envisagé d'y ajouter la possibilité d'exporter les films, mais 1) ce n'est pas du tout l'endroit 2) ce serait de toute façon trop compliqué. L'exportation est un truc qui sera j'espère plus facile à mettre en place avec la version 2.2

Je vais modifier le texte, qui effectivement est trompeur, c'est un oubli.

**Comment by lesurfeur** [comment]
Ok ça marche.
Pour l'exportation des films, une simple liste (inclus que les titres) au format texte suffirait je pense.

**Comment by CaerCam** [comment]
Gros inconvénient de la liste de titres : certains correspondent à plusieurs films... Donc nécessité de refaire certains choix en cas de re-importation. Une liste d'ID TMDb ou IMDb serait beaucoup plus efficace (et légère), je pensais proposer les trois au choix :-)

**Comment by lesurfeur** [comment]
Si on aura la possibilité d'avoir le choix, c'est parfait.
Le plus tôt serait un bonne chose, on est pas à l'abrit d'un plantage sql et de sauvegarde foireuse ou égarée. ;)
En ce qui me concerne se sera le mode liste de titre, car j'ai pas mal de vieux films et DVD musicaux qui ne sont pas dans la base de TMDb que j'ai due créer à la mano et donc pas d'id TMDb (peu être qu'ils s'y trouvent chez IMDb mais cela ne change pas mon problème vu que l'on importe via TMDb et qu'il ne les trouvera pas sur celui-ci).

**Comment by CaerCam** [comment]
Idéalement l'importation devrait de toute façon supporter les listes hétéroclites mélangeant titres, TMDb IDs et IMDb IDs. Ce n'est pas encore fait − le développement de la version 2.2 est en pause pour l'instant pour avancer sur la version 2.1.5 − mais tel que la base est conçue, ça devrait être possible assez facilement. Partant de là c'est cohérent de proposer les trois à l'export également :)

Pour ce qui est du plus tôt malheureusement, ça va être plus compliqué, mon agenda professionnel commence à bien se remplir pour les mois à venir, donc ça risque de demander un peu de temps :disappointed:

**Comment by lesurfeur** [comment]
Pas de problème, je comprend très bien, place au travail en priorité ;)
