### ISSUE TITLE
Currently Update of Metadata

### ISSUE THREAD

**Issue by stargatehome** [wpmovielibrary/wpmovielibrary#253]
Hey Charlie,

I want to know if the metadata of a movie is currently updated or "only" at the import? I think in a later version the metadata should be checked currently, but there should be also an option to turn it off, espacially for the summary of the movie (often written by the editor itself.;)).

Cheers,
Mario

**Comment by CaerCam** [comment]
Yep, metadata are set when importing/adding a movie, never after, but I too have been thinking of a way to update it periodically. The most logical way is probably a CRON job, but that could become a problem on heavy libraries and will require a very thorough thinking prior to any development.

Version 2.2 will include a way to update a movie in a click from the "All Movies" page, probably a batch update too, although I haven't started any development on that part. Single update is easy, multiple update will need a bit more work as it implies sending potentially a lot of requests to the API.

This could also be linked with #168.
