### ISSUE TITLE
Problème de tri avec le widget "Statuts"

### ISSUE THREAD

**Issue by lesurfeur** [wpmovielibrary/wpmovielibrary#255]
Bonjour Charlie,
Lorsque l'on fait un tri des films disponibles, cela renvoie également les films non disponibles.
A l'inverse, le tri avec indisponible, lui fonctionne bien.

![capture](https://cloud.githubusercontent.com/assets/5854465/7101475/bde9ec6c-e05b-11e4-9ec5-d7bf7e3d3dfe.PNG)

**Comment by CaerCam** [comment]
Bien vu ! Essaye avec la dernière version (changement de comparaison, avant c'était du LIKE donc `unavailable` et `available` étaient confondus semble-t-il). Il y aura moyen d'optimiser ce bout de code par la suite.

**Comment by lesurfeur** [comment]
Même problème

**Comment by CaerCam** [comment]
On parle bien du Widget « WPMovieLibrary − Films » avec comme réglages « Afficher les films par… Statut, Disponible » ? Chez moi 9a00dc3d35346ab6a99edba4e1090be69be97d32 a résolu le problème, plus de films indisponibles dans la liste…

Test, dans le fichier `includes/widgets/class-movies-widget.php`, après la ligne 298 (`$movies = new WP_Query( $args );`) ajoutes :


	if ( 'status' == $select )
		var_dump( $movies->request );

**Comment by lesurfeur** [comment]
Oui on parle bien du même ;)
Alors ton nouveau bout de code c'est exactement pareille.

**Comment by CaerCam** [comment]
… Le Widget « Détails » n'affiche pas de films, il n'affiche qu'une liste de détails (notes, médias, statuts…) ; tu es sur qu'on ne parle pas du Widget « Films » ?
