### ISSUE TITLE
runtime improvement

### ISSUE THREAD

**Issue by stargatehome** [wpmovielibrary/wpmovielibrary#257]
Hey Charlie,

I think I found an intresting point. Sometimes the plugin imports (if the runtime is not available 0) and it shows that the runtime is unknown.
![4](https://cloud.githubusercontent.com/assets/9327486/7128490/210545c8-e253-11e4-81f8-bf631bbfba8f.JPG)
![unbenannt3](https://cloud.githubusercontent.com/assets/9327486/7128491/210f2836-e253-11e4-9175-cdfab4a2a087.JPG)
But however it shows sometimes nothing and hadn't imported a number. Maybe it's better to set it to zero by default?
![unbenannt2](https://cloud.githubusercontent.com/assets/9327486/7128497/3c85a23e-e253-11e4-8263-203004e905f1.JPG)
![unbenannt](https://cloud.githubusercontent.com/assets/9327486/7128498/3c8c2b04-e253-11e4-9963-a0c060c707fc.JPG)

Cheers, 
Mario

**Comment by CaerCam** [comment]
Nice catch. It will be fixed in version 2.2 since the new JavaScript part will be able to fill default values properly. If that's really urgent I'll try to patch it for version 2.1.5, if not, well, it'll still be in 2.2 :)
