### ISSUE TITLE
own div class for rating number and enabling numbers in the grid

### ISSUE THREAD

**Issue by stargatehome** [wpmovielibrary/wpmovielibrary#258]
Hey Charlie,

I have two short points for the plugin. First I would rather style the number of the rating:
![unbenannt2](https://cloud.githubusercontent.com/assets/9327486/7128574/a7d1611c-e254-11e4-9594-0d59fe15d9b7.JPG)
![unbenannt](https://cloud.githubusercontent.com/assets/9327486/7128573/a7d1538e-e254-11e4-889e-b658cf52648e.JPG)
So I think another CSS-Class would help. ;)

And maybe you could enable to show up the rating number in the grid (or haven't I found that option?).

Cheers,
Mario

**Comment by CaerCam** [comment]
Replacing the current

	<div class="wpmoly detail rating">
		<div id="wpmoly-movie-rating-538" class="wpmoly-movie-rating wpmoly-movie-rating-4-5" title="4.5/5 − Excellent">
			<span class="wpmolicon icon-star-filled"></span>
			<span class="wpmolicon icon-star-filled"></span>
			<span class="wpmolicon icon-star-filled"></span>
			<span class="wpmolicon icon-star-filled"></span>
			<span class="wpmolicon icon-star-half"></span>
		</div>
	</div>
	&nbsp;−&nbsp;4.5/5

With something like

	<div class="wpmoly detail rating">
		<div id="wpmoly-movie-rating-538" class="wpmoly-movie-rating wpmoly-movie-rating-4-5 wpmoly-movie-rating-with-label" title="4.5/5 − Excellent">
			<span class="wpmolicon icon-star-filled"></span>
			<span class="wpmolicon icon-star-filled"></span>
			<span class="wpmolicon icon-star-filled"></span>
			<span class="wpmolicon icon-star-filled"></span>
			<span class="wpmolicon icon-star-half"></span>
			<span class="rating-separator">−</span>
			<span class="rating-label">4.5/5</span>
		</div>
	</div>

Would help, wouldn't it? More customization possibilities.

**Comment by stargatehome** [comment]
Yeah should be all I need. ;)
