### ISSUE TITLE
new widget proposal

### ISSUE THREAD

**Issue by stargatehome** [wpmovielibrary/wpmovielibrary#259]
Hey Charlie,

I have an idea for an new but hopefully not so complicated widget. Gladly I wanna show the newest movies in the database as a list, but only the titels; not any more. In a way that function exist with the movie-widget but then there is still the space for the posters in the widget and you cannot style the way you want it, because there are some CSS-Options missing.

Hope I gave some approaches. 

Cheers,
Mario

**Comment by CaerCam** [comment]
A new Widget would be a bit exaggerated, but adding an option to show a classic `<ul>` list is a good idea anyway :)
