### ISSUE TITLE
only showing rated movies

### ISSUE THREAD

**Issue by stargatehome** [wpmovielibrary/wpmovielibrary#262]
Hey Charlie,

is there an option to show only rated movies?

Cheers,
Mario

PS: Working on translating the new files. :)

**Comment by CaerCam** [comment]
You mean in the grid, exclude movies with no rating set?

**Comment by CaerCam** [comment]
(oops, closed by mistake)

**Comment by stargatehome** [comment]
Yeah, wanna have a grid with only rated movies. :) And maybe a widget, only including rated movies, but with all the other options of the movie-widget. :)
