### ISSUE TITLE
Importer les images des acteurs - Question

### ISSUE THREAD

**Issue by lesurfeur** [wpmovielibrary/wpmovielibrary#266]
Bonjour Charlie,

Ne serait-il pas possible d'importer les photos des acteurs et que l'importation se fasse dans 'term_description' des acteurs ? (l'API le permet me semble t'il, la mise en place est une autre chose ;) )
Cela serait pas mal, non ? puisque l'on peut mettre une description dans les terms autant s'en servir.
J'ai juste autorisé le html dans les descriptions (dans mon exemple ci dessous) pour afficher l'image et utiliser les balises avec : 
foreach ( array( 'pre_term_description' ) as $filter ) {
    remove_filter( $filter, 'wp_filter_kses' );
}
 
foreach ( array( 'term_description' ) as $filter ) {
    remove_filter( $filter, 'wp_kses_data' );
}

![capture](https://cloud.githubusercontent.com/assets/5854465/7433823/83a77a3a-f035-11e4-8600-562ab7598433.PNG)

Ce qui donne par exemple avec le header allociné : 
Après (avec utilsation term_description) : 
![capture](https://cloud.githubusercontent.com/assets/5854465/7446004/668c5426-f1c9-11e4-95c9-45e4b0139a3c.PNG)

Avant (sans term_description) : 
![capture2](https://cloud.githubusercontent.com/assets/5854465/7446005/705ae328-f1c9-11e4-95a2-d59bbc9d0b17.PNG)

**Comment by stargatehome** [comment]
Hey,

seems to be a great improvement? Will you provide the code? Sorry, not speaking french. :D 

Cheers,
Mario

**Comment by CaerCam** [comment]
Using terms to was my first idea to implement actors pics, but I quickly changed my mind as it has quite a few downsides and decided not to put it in the core in that form. I still plan to build a People plugin for this (and much more) feature, and I believe using a custom post type will make it more useful. Easier to add metadata support, multiple images download, interconnection with movies based on imported/not imported movies, etc.

If you share your code it could make a really great transitional feature, but it's unlikely to be compatible with the future People extension.
