### ISSUE TITLE
Headbox styling

### ISSUE THREAD

**Issue by lukezona** [wpmovielibrary/wpmovielibrary#268]
Hi, I'm looking for a way to use an uploaded image as the headbox background (I'm going to make it full width and full height) to create something like PopCorn Time view..

I can't find a way to use the uploaded images instead of the poster..
Where can I edit the code to make it work?

Thanks a lot,
Luca

**Comment by CaerCam** [comment]
Hi there Luca,

You can override most of the frontside templates in your theme by copying the files path; for example with your question about the headbox, create a `wpmovielibrary/movies/` folder in your theme's folder and copy the plugin's `views/movies/movie-headbox.php` into it. Then edit that file the way you want! The original file looks like this:

```php
<?php
/**
 * Movie Metadata view Template
 * 
 * Showing a movie's head box.
 * 
 * @since    2.0
 * 
 * @uses    $items
 */
?>

	<div id="movie-headbox-<?php echo $id ?>" class="wpmoly block headbox contained <?php echo $theme ?>" style="background-image:url(<?php echo $headbox['poster'] ?>);">
		<div class="wpmoly headbox movie poster">
			<div class="wpmoly headbox movie details-3"><?php echo $headbox['details_3'] ?></div>
			<h3 class="wpmoly headbox movie title"><a class="wpmoly headbox movie link" href="<?php the_permalink(); ?>"><?php echo $headbox['title'] ?></a></h3>
			<h4 class="wpmoly headbox movie subtitle"><?php echo $headbox['subtitle'] ?></h4>
			<div class="wpmoly headbox movie details-1"><?php echo $headbox['details_1'] ?></div>
			<div class="wpmoly headbox movie details-2"><?php echo $headbox['details_2'] ?></div>
<?php echo $menu ?>
		</div>
<?php echo $tabs ?>
	</div>
```

To get rid of the background poster just remove the ```style="background-image:url(<?php echo $headbox['poster'] ?>);"``` part of line 13, or replace it with any image you want to use.

**Comment by lukezona** [comment]
Thanks, I was looking for that..

One last question: instead of $headbox[poster] I would like to use an image uploaded from your plugin (I choose it in 'Images' in the plugin section), I haven't found any shortcode like $headbox[poster]..

Thanks a lot

**Comment by lukezona** [comment]
Sorry for bothering you but I've tried to find out myself and I found out that's the template_render function that fills all the fields up, no way to understand how (I'm a bit noob =D)..

I was looking for something easyer to make something like the movie-modal admin page (I only need the link or a php code to put the image chosen from Images section as background image)

Sorry again for the bother

**Comment by CaerCam** [comment]
Images (and Posters) are regular WordPress Attachments, meaning you can fetch them just as any other WordPress content using `get_posts()`. The plugin lacks an internal function to get images, but meanwhile you can use this:

```PHP
$image = get_posts( array(
	'meta_key'    => '_wpmoly_image_related_tmdb_id',
	'post_type'   => 'attachment',
	'numberposts' => 1,
	'post_status' => null,
	'post_parent' => $id,
) );
```

This should get you one image related to the movie of ID `$id`. Applied to the Headbox, paste this Gist into a `wpmovielibrary/movies/movie-headbox.php` file in your theme's folder: https://gist.github.com/CaerCam/8a32250014fb0b86cc2b

**Comment by lukezona** [comment]
Thanks a lot, it works like a charm..
