### ISSUE TITLE
adding movie pictures through wordpress database

### ISSUE THREAD

**Issue by stargatehome** [wpmovielibrary/wpmovielibrary#269]
Hey Charlie,

could you add the option to add movie pictures through the wordpress media database? Would be great, because at the moment there is no option to do so. ;) Is it difficult? Would be very nice. :) 

Cheers, 
Mario

**Comment by CaerCam** [comment]
It's, planned, and actually it's already done in the dev version 2.2 ;-)  That version supports user images/posters upload directly from the editor, just like regular posters/backdrops :-)

**Comment by stargatehome** [comment]
Great! :) But the problem is the dev-version 2.2 doesn't work for me. I can't import movies or even switch to other settings than the metadata of a movie. :/ But I really like the new design. :)
