### ISSUE TITLE
Grid-Navigation is broken

### ISSUE THREAD

**Issue by stargatehome** [wpmovielibrary/wpmovielibrary#275]
Hey Charlie,

there is some trouble with the plugin, the grid-navigation isn't working anymore. Every time I click on a letter etc. it leads to the "normal" grid, as it was before. So there is not really anymore a way to find a movie... :/

Cheers,
Mario

**Comment by CaerCam** [comment]
Indeed, the URL for letters are not correctly built; [manually formed URLs](http://film-freak.net/filme/grid/letter/B/6:4/title/ASC/) work, though. I'll take a look at this, thanks for reporting!

**Comment by stargatehome** [comment]
And any ideas?

**Comment by stargatehome** [comment]
Hey Charlie, 

Do you yet have an idea, how to fix that? Would be great. :)

Cheers

**Comment by CaerCam** [comment]
I'm afraid not :/ This part of the plugin is a nightmare to debug, relying way too much on URLs… And it's all going to be wiped out with version 2.1.5, anyway. I've got back to work on that part last week, and it's starting to look like something useful at last :)

**Comment by stargatehome** [comment]
Ok, please contact me if theres a test-version. :)
