### ISSUE TITLE
movies not shown in search

### ISSUE THREAD

**Issue by stargatehome** [wpmovielibrary/wpmovielibrary#276]
Hey Charlie,

the "movies shown in search" - function doesn't work for me. :/ Any ideas?

Cheers,
Mario

**Comment by CaerCam** [comment]
How so? [That search](http://film-freak.net/?s=harry+potter) shows a movie in the result. Is there anything missing?

**Comment by stargatehome** [comment]
It was only possible for with adding this code to my functions.php:
```php
function include_post_types_in_search($query) {
	if(is_search()) {
		$post_types = get_post_types(array('public' => true, 'exclude_from_search' => false), 'objects');
		$searchable_types = array();
		if($post_types) {
			foreach( $post_types as $type) {
				$searchable_types[] = $type->name;
			}
		}
		$query->set('post_type', $searchable_types);
	}
	return $query;
}
add_action('pre_get_posts', 'include_post_types_in_search');
```

**Comment by stargatehome** [comment]
Also that option doesn't work...
![unbenannt](https://cloud.githubusercontent.com/assets/9327486/8282156/dbbc457a-18ee-11e5-9f37-e8388369c847.JPG)
