### ISSUE TITLE
Updating post timestamp with movie release date

### ISSUE THREAD

**Issue by pavlosadovyi** [wpmovielibrary/wpmovielibrary#277]
Hi! I saw that plugin is updating post title with movie title and want to do exactly the same but with post timestamp and movie release date. So if I add old movie it will not appear on recently posts widget. Could you point me how to do that?

**Comment by CaerCam** [comment]
Hi Pavlo,

I like the idea! I'll probably add this in a future version. Meanwhile, you can achieve this by adding [that code](https://gist.github.com/CaerCam/03d1a121b7235b083f54) to your theme's `functions.php` file :)
