### ISSUE TITLE
Poster image from TMDB

### ISSUE THREAD

**Issue by pavlosadovyi** [wpmovielibrary/wpmovielibrary#279]
Hi,

My hosting plan have only 500MB of disk space and I met a problem when I reach 270 movies.
The first idea in my head was copy all images from FTP, resize them with automation in Photoshop, put it back and wait for another apocalypse.

Proposal 1: some option for resizing large posters to for example 300x400 px when upload
But can't we somehow get poster image url from TMDB to show? And store only this url in DB?
Any ideas? Thank you in advance

**Comment by CaerCam** [comment]
Hi Pavlo,

In the Settings panel, under Images > Posters > Poster Default Size you can can chose what size the posters should have; default is set to the `original` size, but by setting it to `medium` or `small` you will have smaller images.

As for the URL-only saving, that's something that would be consistent with #168 so it'll probably exist at some point :)

**Comment by silkweb1** [comment]
Sorry to hijack this question but I have a similar issue with image poster size.  Even when I change the size in the settings the poster is still the full size of the page....how do I get it to show as the size I have indicated?

**Comment by lesurfeur** [comment]
HI Silkweb1,

If you have already recorded movies with the setting of the size of posters 'full size' and you've changed the settings after 'smaller', it's normal. You must edit your movie pages and re-download the posters (not forgetting to delete old). The parameter change does not affect the old posters already downloaded.

**Comment by CaerCam** [comment]
Spiky said it all :-)

**Comment by pavlosadovyi** [comment]
Sorry for rising up this question, but how can I resize poster image to specific size (coz on tmdb posters has different height), 200x300 right after upload? I tried this, no luck:

admin/class-wpmoly-media.php
```php
$id = media_handle_sideload( $file_array, $post_id );
// my code
$path = wp_get_attachment_url( $id );
if (file_exists( $path )) { // Fails: file does not exist yet
    $image = wp_get_image_editor( $path ); // WP_Image_Editor

    if ( ! is_wp_error( $image ) ) {
        $image->resize( 200, 300 );
        $image->save( $path );
    }
}
```
file_exists fails, but I can access that file manually, it seems at that moment in image_upload() isn't exist, maybe some hook exist like after_attachment_upload?

**Comment by CaerCam** [comment]
Hi there Pavlo,

You're using the image's URL, but did you tried using the path instead? `wp_get_image_editor()` is _supposed_ to work with either the URL or the path, but will actually work better with path, so using `$path = wp_get_attachment_image_src( $id, 'full' );` instead of `$path = wp_get_attachment_url( $id );` would be a good start :)

**Comment by pavlosadovyi** [comment]
SOLVED
If you've meet the same problem add this to your functions.php:
```php
add_action( 'add_attachment', 'fukasawa_poster', 10, 1 );
add_action( 'edit_attachment', 'fukasawa_poster', 10, 1 );

function fukasawa_poster($attachmentID) {
  $attachment = get_attached_file($attachmentID);
  if (file_exists( $attachment )) { // Fails: file does not exist yet
    $image = wp_get_image_editor( $attachment ); // WP_Image_Editor

    if ( ! is_wp_error( $image ) ) {
        $image->resize( 200, 300 );
        $image->save($attachment);
    }
  }
}
```

It will scale original image to 200x300 without any duplication like filename-200x300.jpg
Also you can use wp-imgur plugin to store all your Media Library on Imgur ;)

**Comment by CaerCam** [comment]
Thanks for that fix! I really like the idea to automatically resize the posters to a standard 3/2 size. Maybe in a future update :)

**Comment by lesurfeur** [comment]
Pour ma part je passe par le fichier fonction du theme mais effectivement cela duplique les images et donc augmente le stockage sur le disque. Et part la même occasion toute les images importées sont définies par cette régle dans le fichier function.php de mon thème ex:
~~~~
	// Post thumbnails
	add_theme_support( 'post-thumbnails' );
	set_post_thumbnail_size ( 120, 160, true );
	
	add_image_size( 'archive-movie-poster', 185, 255, true );
	add_image_size( 'single-movie-poster', 284, 388, true );
~~~~

Si je comprend bien avec sa méthode cela impacterai que les images importées par le plugin ?

**Comment by CaerCam** [comment]
Non, le bout de code de Pavlo impactera toutes les images importées… Il faudrait ajouter une vérification du post type, ce qui peut être un peu tordu dans le contexte.

**Comment by lesurfeur** [comment]
Ok ok j'avais mal lu car je pensai qu'il modifiait le fichier admin/class-wpmoly-media.php comme cité plus haut alors que c'est le fichier functions.
Merci pour ta précision.
