### ISSUE TITLE
are movies custom post-types?

### ISSUE THREAD

**Issue by stargatehome** [wpmovielibrary/wpmovielibrary#280]
Hey Charlie, 

can I use movies as normal custom post-types?

Cheers,
Mario

**Comment by CaerCam** [comment]
Hi Mario,

Not sure what you mean by "normal custom post types", but anyway, movies are indeed a custom post type set up by the plugin :-)

**Comment by stargatehome** [comment]
Hey Charlie,

thats great, so it should  be easy to show them as "normal" custom post types and creating other ways to list movies. ;)

Cheers,
Mario

**Comment by CaerCam** [comment]
Yeah, that's exactly the point of using a CPT ;-)
