### ISSUE TITLE
better documentation of function

### ISSUE THREAD

**Issue by stargatehome** [wpmovielibrary/wpmovielibrary#283]
Hey Charlie,

I've tried your solution for using functions or that you've said it is better to use them, but I have problems getting the functions without shortcodes. I think the most would be enough, like getting movie meta, thumbnail, rating and images.

Cheers,
Mario

Thanks man. :)

**Comment by CaerCam** [comment]
Yeah, the docs is clearly missing on that part. There's a handful of functions you can use:

Get movie complete meta (`$meta = 'data' or 'meta'`), complete details (`$meta = 'details'`) or specific meta/detail (`$meta = 'release_date'`, `$meta = 'rating'`)
`wpmoly_get_movie_meta( $post_id, $meta = 'data' );`

Get movie complete details
`wpmoly_get_movie_details( $post_id );`

Get movie status detail
`wpmoly_get_movie_status( $post_id );`

Get movie media detail
`wpmoly_get_movie_media( $post_id );`

Get movie rating detail
`wpmoly_get_movie_rating( $post_id );`

Get movie languages detail
`wpmoly_get_movie_language( $post_id );`

Get movie subtitles detail
`wpmoly_get_movie_subtitles( $post_id );`

Get movie format detail
`wpmoly_get_movie_format( $post_id );`

Check if movie has meta/detail
`wpmoly_has_movie_meta( $meta, $value );`
