### ISSUE TITLE
how to get the details language and subtitles via shortcode

### ISSUE THREAD

**Issue by stargatehome** [wpmovielibrary/wpmovielibrary#285]
See the title. :)

Cheers,
Mario

**Comment by lesurfeur** [comment]
Hi,
The list of the shortcode is here: http://wpmovielibrary.com/documentation/shortcodes/

**Comment by stargatehome** [comment]
Know that list. ;) But the detail language is not listed there. Only the meta language... :)

**Comment by CaerCam** [comment]
The list is probably out of date, anyway… You should be able to get those values with these functions, though:

```PHP
$language = wpmoly_get_movie_language( $movie_id );
$subtitles = wpmoly_get_movie_subtitles( $movie_id );
`

In any case, it's just regular WordPress post meta, so you can access them like any other meta: `get_post_meta( $movie_id, '_wpmoly_movie_subtitles' )` or `get_post_meta( $movie_id, '_wpmoly_movie_language' )`
