### ISSUE TITLE
own media?

### ISSUE THREAD

**Issue by stargatehome** [wpmovielibrary/wpmovielibrary#286]
Hey Charlie,

I think the media detail cannot work as it should be. For example there is not one version of a DVD of a movie mostly there will be a Director's Cut etc. and so I think it would be better to give an custom field where the user can only add text to save his media.

See the picture.
![unbenannt](https://cloud.githubusercontent.com/assets/9327486/8612230/45fbad68-26cd-11e5-8986-aba4239a08e7.JPG)

Cheers,
Mario

**Comment by lesurfeur** [comment]
Hi,
I do not agree, the support is a DVD, after this is just a version of the film. You can create another module in addition to the version of the film director cut, long version ect ...

**Comment by CaerCam** [comment]
Absolutely.

Details in general and Media in particular are important data, used in various ways throughout the plugin, be it to display data, generate icons or filter search. No way we let users put what they want in there unless we want to have erratic behaviour all over the place :)

**Comment by itroll42** [comment]
I've been trying to determine how to add more "detail options" like in the post that lesurfeur commented on Jul 12.  Specifically I'd like to add the audio format.  Keeping it as a drop down selection like the other details options are fine.

I guess the question is CaerCam says that details are extendable via plugins.  But I haven't been able to find any plugins that would allow me to add things like in lesurfeur's post.  Maybe I just can't find it, but any help would be appreciated.

**Comment by lesurfeur** [comment]
Hi itroll42,
My plugin here : https://github.com/lesurfeur/WordPress/tree/master/Plugin

**Comment by itroll42** [comment]
lesurfeur,
  Thanks for the link.  I downloaded that and installed the details audio plugin.  However it now looks like the server i'm hosted on only has php 5.3.3.  So I have put an email in asking if that can be updated to 5.4 since that is what your plugins require.
