### ISSUE TITLE
how to get only the release year

### ISSUE THREAD

**Issue by stargatehome** [wpmovielibrary/wpmovielibrary#288]
Hey Charlie,

the title says everything. I know it's possible because of the default head-design, but I haven't found a solution yet. Neither through shortcodes nor with methods...

Ideas?

Cheers and I'm looking forward to your develompment! :)

Mario

**Comment by CaerCam** [comment]
Well, the simplest way once you get the release year is to use some basic PHP: `$year = substr( $release_date, 0, 4 )`. The release date should always be in `YYYY-MM-DD` format so extracting the first 4 characters will give you the year :)
