### ISSUE TITLE
Disfonctionnements

### ISSUE THREAD

**Issue by lesurfeur** [wpmovielibrary/wpmovielibrary#289]
Bonjour Charlie,

Je relève trois disfonctionnements : 
1 - Les images importées avec les films ne s'effacent pas lors de la suppression d'un films. Réglages pourtant sélectionné dans les options (les posters par contre c'est ok).
2 - L'API doit avoir de nouvelles restrictions ? Ou problème ponctuel ? car j'ai essayé d'importer 52 films, cela me met bien 52 films importés, mais lorsque je souhaite chercher les métadonnées ça les trouvent que par 5 ou 7 voir 9 maxi avec une erreur affichée " Erreur de l'API : la connexion à "http s://api.themoviedb.org/3/search/movie?api_key=XXXXXXX&query=NOMDUFILM&page=1&language=fr&include_adult=0" a renvoyé une erreur 429 : "
Et donc obligé de décocher à chaque fois les films dont les métadonnées n'ont pas été importés, un peu agassant...

3 - En ajoutant les films trouvés avec métas (par exemple 7 films) en fil d'attente, il y a quelques problèmes également, un exemple : " Une erreur s’est produite lors de l'ajout de « Forrest Gump » à la file d'attente : Identifiant de l’article non valide. " et du coup cela bloque le processus et aucun ne s'y met.

**Comment by CaerCam** [comment]
Je n'ai pas eu vent de nouvelles restrictions sur l'API, mais l'erreur 429 caractérise effectivement un nombre trop important de requêtes… Je n'arrive pas à reproduire ça chez moi.

L'importeur est de toute manière en fin de vie, j'espère trouver rapidement assez de temps pour reprendre le développement de la version 2.2, il y en a GRAND besoin…

**Comment by lesurfeur** [comment]
Je pense qu'il y a une limitation, j'ai retesté plusieurs fois avec 10 films et le résultat diffère entre 4, 5 et 6 maximum résultats de retournés. En les selectionnants manuellement via l'icone dans Actions->Télacharger les données  cela fontionne bien.

**Comment by CaerCam** [comment]
Ce n'est pas impossible, tout dépend de la vitesse à laquelle s'enchaînent les requêtes… Je n'ai jamais eu ce problème, mais ce n'est pas mpossible.
