### ISSUE TITLE
problems with settings

### ISSUE THREAD

**Issue by carolinanicolau** [wpmovielibrary/wpmovielibrary#290]
Hey Charlie

Thanks for the plugin, its awsome. I'm changing my whole review website to adapt to it.

I'm having some problems though. When I try to change some settings options, I save it and it returns to original options. 
For exemple, I can't enable movies search because everytime I change to "enable", both the enable and disable buttons are collored and when I hit save it goes back to only disable. 

I searched here and didnt seem to find anyone experimenting the same issues. Also, I thought it might be a problem with php, but I updated for 5.4 and everything seems to be working fine apart from that options problem.

**Comment by CaerCam** [comment]
Hi carolinanicolau,

Did you ever get this sorted?
