### ISSUE TITLE
Grid (sorting) options doesn't work

### ISSUE THREAD

**Issue by mzk23** [wpmovielibrary/wpmovielibrary#291]
Hi,

first of all - great plugin, thank you for doing it.

So as I mentioned in title, sorting options in movies grid like a letter or button "All" doesn't work for me. When I click on "All" or letter "S" for example, it gives me 404 error. I tried with permalinks, but nothing works. 

site.com?columns=4&rows=7&order=DESC&orderby=title&view=grid and site.com/grid/4:7/title/DESC gives me 404. 

I don't have any additional plugins.

I would appreciate your help.
Thanks

**Comment by CaerCam** [comment]
Hi mzk23,

There are real issues with the grid sorting in current/previous version, due to the fact it uses permalinks… I'm working on a better solution for the grid for the next big update!
