### ISSUE TITLE
Ordre d'affichage

### ISSUE THREAD

**Issue by lesurfeur** [wpmovielibrary/wpmovielibrary#292]
Salut Charlie,

Je suis en train de peaufiner mon thème et je souhaiterai modifier l'ordre d'affichage d'un élément.
Le "block détails" s'affiche avant le "block meta" et je souhaiterai inverser cet ordre.
Je ne trouve pas ou modifier cela.

Actuellement cela s'affiche comme ceci : 
![wpmoly](https://cloud.githubusercontent.com/assets/5854465/9154853/0608babe-3ea3-11e5-8203-25d5ba19bb46.PNG)

Et je souhaiterai le placer ailleurs, en dehors de la div post-content, comme ceci :

![wpmoly](https://cloud.githubusercontent.com/assets/5854465/9154906/07c9b07c-3ea5-11e5-94e7-e2a98eb47eec.PNG)

**Comment by lesurfeur** [comment]
Pas de solution ?

**Comment by CaerCam** [comment]
Salut Spiky,

Désolé pour l'attente :( Plus d'un mois, on frôle le record… Ce n'est pas modifiable directement, donc je viens d'ajouter un filter pour pouvoir modifier l'ordre, `wpmoly_movie_vintage_content`. Quatre paramètre : le contenu final ou presque en HTML (details + metadata), le contenu du bloc details, le contenu du bloc metadata, et le contenu original. Du coup pour changer l'ordre des blocs ce bout de code devrait fonctionner :

```php
function edit_vintage_content( $html, $details, $metadata ) {
    return $html = $metadata . $details;
}
add_filter( 'wpmoly_movie_vintage_content', 'edit_vintage_content', 10, 3 );
```

**Comment by lesurfeur** [comment]
Bonjour Charlie,
Super cela fonctionne impec.
Une option bien utile en tout cas qui pourrait figurer dans le panneau des réglages ;)

Merci beaucoup.

**Comment by CaerCam** [comment]
Pas de soucis !

Une option risque de faire doublon avec le hook, d'autant que l'impact est limité – la plupart des utilisateurs semblent conserver les headboxes – mais s'il y a de la demande ça sera envisageable oui :-)
