### ISSUE TITLE
Deleting movie not delete attachments from Media Library

### ISSUE THREAD

**Issue by pavlosadovyi** [wpmovielibrary/wpmovielibrary#293]
When I delete movie, not poster nor images will not be deleted from media library, even the corresponding option is enableed in settings. Probably the problem in delete_movies_attachments(), I starred at code and it should work, but not for me. :(

**Comment by CaerCam** [comment]
Hi Pavlo,

Okay, @lesurfeur  mentioned that issue on #289, I'll take a look at this bug.
