### ISSUE TITLE
Besoin d'aide affichage taxo, terms, meta ect...

### ISSUE THREAD

**Issue by lesurfeur** [wpmovielibrary/wpmovielibrary#294]
Bonjour,

Besoin d'aide, je suis un peu perdu avec les taxo, terms...

Voila, je souhaite afficher en haut de ma page le pays, la date quand je suis sur ces pages comme je le fais pour les taxo genre,actor et collection : 
![capture](https://cloud.githubusercontent.com/assets/5854465/9633915/764dd8fa-518f-11e5-8538-4fb8c6e83c6f.PNG)
![capture2](https://cloud.githubusercontent.com/assets/5854465/9633923/7bd65be4-518f-11e5-91f8-c1ee4e0fcc9c.PNG)
![capture3](https://cloud.githubusercontent.com/assets/5854465/9633930/8085e60a-518f-11e5-8a89-03635c0db602.PNG)

Pour ma page archive j'utilise : 
~~~
<?php elseif ( is_post_type_archive() ) : ?>
<?php echo post_type_archive_title(); ?>
~~~
Pour les taxo j'utilise dans mes templates "taxonomy-XXX.php" : 
~~~
<?php echo single_tag_title(); ?>
~~~
Qu'elles sont les pages a créer et le code pour afficher les postmeta ?

**Comment by lesurfeur** [comment]
Bon alors, je n'ai toujours pas réussi a faire ce que je voulais.
Je souhaiterai en faite sans utiliser l'option "Archives des taxonomies -> Réglages des archives de films -> Page d'archives des films -> Choisissez une page à utiliser comme archive de films."
pouvoir afficher les metas en titre de page.

Je ne veux pas utiliser cette option car elle fonctionne avec la grille que tu as créé, sinon je perd mon template.

Merci pour ton aide.

**Comment by zack06007** [comment]
En page d'archive de film, lorsqu'on rentre dans le menu j'aurai bien aimé afficher la page du A a la place du 0, voir une lettre aléatoire, histoire que quand mes gens y vont ils ne vont pas toujours les mêmes films - je parle lorsqu'on rentre dans le menu, après le reste fonctionne normalement 

Envoyé de mon iPhone

**Comment by CaerCam** [comment]
La modification du titre dans les pages d'archives est effectuée en utilisant les filtres `wp_title` et `the_title` ; c'est la méthode `movie_archives_title()` de la classe `WPMOLY_Archives` (`public/class-wpmoly-archives.php`) qui génère les titres. En l'état cette méthode n'est pas utilisable si on utilise pas les pages d'archives, mais je vais réfléchir à comment l'adapter pour qu'elle fonctionne sur les pages d'archives classique.

**Comment by lesurfeur** [comment]
Ok merci cela serait un plus pour ceux qui ne souhaite pas utiliser la grille mais leur propre mise en page (ou celle d'origine de wp).
