### ISSUE TITLE
How to make rating public

### ISSUE THREAD

**Issue by pavlosadovyi** [wpmovielibrary/wpmovielibrary#295]
It seems, that only admin of the blog can rate movies in library. How can I give possibility my readers to vote? Point me please

**Comment by webstractions** [comment]
What you are looking for is [WPMovieLibrary Advanced Rating](https://github.com/wpmovielibrary/wpmovielibrary-advanced-rating) extension. It implements advanced movie ratings: direction, soundtrack, vfx, etc. Plus user ratings. 

Currently, not sure if this extension works at all. Charlie has not had much time to work on it.

**Comment by CaerCam** [comment]
@webstractions is right, that kind of feature was planned for extensions. Unfortunately I haven't had any time to work on it… That's part of the things that will have to wait until the major work on the core plugin is done :(

**Comment by rakeem2k** [comment]
Why the plugin cant get the ratings from tmdb ?
