### ISSUE TITLE
Référencement (Grid)

### ISSUE THREAD

**Issue by zack06007** [wpmovielibrary/wpmovielibrary#296]
Bonjour Charlie,

J'espère que tu vas bien depuis le temps? Alors des news pour ton module WPML? [Dream Mode on] Un module communautaire [Dream Mode off]? Tu sais que beaucoup d'entre nous l'utilisons au quotidien et que c'est toujours aussi brillant.

J'ai eu deux fois une remonté sur un film introuvable sur le référencement (Grid), alors que le film y était. En effet , je t'en avais parlé, lorsqu'il y a un espace, un trait-d'union ou une apostrophe, il le prend comme une lettre et donc classe le film au mauvais endroit. Ne peut on pas avoir une option pour exclure la prise en charge de ces termes? (exemple C: http://www.cinechezmoi.fr/referencement/grille/C/6:12/title/ASC/)

De plus, dans l'affichage par liste, ne peut-on pas avoir la possibilité d'un affichage en deux colonnes - et comme y a pas d'images, mettre afficher "tout" pour avoir une liste entière. Je suis dans de l'indexation de page et ça permettrait d'avoir tout d'un coup d'oeil - et pour les visiteurs ca permettrait d'avoir un regard plus élargit sur toutes les fiches de film. 

Sinon quoi d'autres? Rien car c'est parfait. Après je suis toujours preneur de nouveautés comme un module suggestions (d'ailleurs dispo sur Amazon en f/ des achats).

Amicalement
zack

**Comment by CaerCam** [comment]
Tout ce qui est apparence de la grille (liste, colonnes, etc) sera beaucoup plus facile avec la version 2.1.5 puisque la grille fonctionnera en JavaScript avec chargement des films en AJAX (sans rechargement de la page, donc) ; on pourra choisir le nombre de films par colonne (grille), le nombre de colonnes (liste) et voir la modification immédiatement :)

Pour ce qui est du classement sans « l' » et autres « Le/La/Les/A », j'ai longuement réfléchi à la question, et je pense que ça ne sera pas implémenté. J'ai fait beaucoup de tests, c'est au mieux peu fiable, avec des conflits réguliers dans le classement (si on essaie de classer des films par pays ou par date, avec en plus une exclusion des « le/la/les ») et au pire un ralentissement énorme des requêtes…

En fait ma conclusion personnelle est que cela relève d'avantage d'un choix éditorial que d'un choix technique. Certaines médiathèques classent les films ou les BD par titre ou série, d'autres par auteurs… Il sera largement plus efficace d'adapter le titre des fiches à cette norme plutôt que de tenter de la forcer techniquement. Ainsi un simple tri par titre de post, c'est-à-dire le comportement par défaut de WordPress, donnera le résultat voulu. Dans un second temps, par contre, on peut envisager une option pour utiliser non pas le titre de post, mais le titre méta du film pour l'affichage, avec une réserve toutefois car cela pourrait s'avérer compliqué à maîtriser selon que l'on veut un remplacement partout ou seulement à certains endroits.

Bref, il y a encore matière à réflexion :)

**Comment by zack06007** [comment]
Super pour le javascript. j'ai hâte.

Par contre je parlais pas des Le/La/Les, j'ai toujours géré sans, même quand je tenais le forum en phpbb je n'ai jamais utilisé les articles définis et je préfère ainsi, comme ça je fais pareil pour le "The" en anglais. Instinctivement je vais écrire le titre "Main au collet (La)". Sur ce point pas de souci je ne changerai pas et ça ne pose pas de souci, La normalisation est correct, techniquement le système n'a rien besoin de gérer/exclure.

Le souci vient des espaces, des points ou de l'apostrophe.
En effet, par exemple "M le Maudit", il va me le mettre en début de liste, avant le MA... alors que logiquement il devrait me le mettre à la position ML.... Idem pour "A Vif" ou dernièrement "A la poursuite de demain".  Après rien de bien marquant mais au début de certaines lettres y a plein de film qui ne devrait pas être là.

**Comment by CaerCam** [comment]
Au temps pour moi, je n'avais pas saisi la distinction. Cela dit le problème reste le même, c'est excessivement lourd à traiter au niveau des requêtes, et cela entraîne des incohérences dans certains cas… Personnellement j'irais naturellement chercher _M le Maudit_ ou _A Single Man_ respectivement au début des M et des A, pas au milieu, mais c'est plus un question d'habitude j'imagine.

Une solution possible serait d'ajouter un champ dans les détails pour saisir un titre à utiliser pour le classement, mais ça aura là aussi un impact important niveau stockage de données, et toujours un ralentissement des requêtes… Je reste assez convaincu que la meilleure solution serait d'utiliser le titre du poste pour influer sur le classement − par exemple en intitulant les posts _Mle Maudit_ et _ASingle Man_ − et utiliser le titre métadonnée du film à l'affichage, mais la réserve mentionnée plus haut demeure.

**Comment by zack06007** [comment]
Ok je verrai pour corriger (ou non) ces quelques exceptions. Si c'était facile ca aurait été bien, mais vaut mieux avoir deux titres à la mauvaise place (dans la base quoi qu'il en soit!), qu'une base qui ralenti à cause d'un correctif pas fiable ou trop lourd. Merci à toi, je continue à te suivre, utilisant au quotidien ton extension!

**Comment by lesurfeur** [comment]
Pour moi, je ne vois rien d'illogique la dedans, c'est normal que "M le maudit" soit avant un titre comme "Man...", la logique de classement est respecté.
Je ne comprend pas trop ton raisonnement zack.

**Comment by zack06007** [comment]
Allez va pour cet exemple, c'est pas le meilleur. 
Pour C'est arrivé près de chez vous, tu le vois au début avant "Ca"  ou à "Ce..." ?

**Comment by lesurfeur** [comment]
Les symboles non alphanumériques, sont classés actuellement avant.
Ex: 
C’est arrivé près de chez vous
C’est pas moi, c’est lui
Cadavres exquis
Cadet Rousselle
Candide
Carnaval
Carrie : La Vengeance
Cars
Cartel
Casimir
...

Après il faut déterminer un ordre, qui n'est "logique" qu'en fontion de la langue, la norme typo, et ici en l'occurence informatique (jeux de caractère...). Bref de logique il n'y en a pas, des règles plutôt (qui peuvent varier selon).

Mais si tu reste dans la logique d'un classement de titre d'ouvrages (que tu sembles utiliser), les articles définis et ce quelle que soit la langue (le, la, les, l’ en français, the en anglais, la, lo, li en italien, die, das, der en allemand, etc...) sont à ignorer dans le classement.
Et donc pour répondre à ta question posé et en respectant la ~~logique~~ règle que tu utilises, le titre "C'est arrivé près de chez vous" devrait être classé dans la lettre E.

Ceci est très bien mais dans le cadre d'un projet participatif il convient de définir la régle clairement sinon cela devient vite le bazar.

Donc, pour ma part, il convient d'utiliser la règle fixé par le system pour moins d'inconvénient.

**Comment by zack06007** [comment]
La logique de l'article défini je l'applique et c'est ce qui reste de plus logique.
C'est - ou Ce sont - ne sont pas des articles défini et devrait etre classé comme n'importe quel terme.

**Comment by lesurfeur** [comment]
C'est bien pour cela que je dis que de logique il n'y en a point mais des règles...
Surtout en language informatique, tu pourras toujours arriver à le faire mais avec un certains prix (temps, traitement...). Certains préféreront une liste continue ou discontinue. Mais si tu lui donnes comme règle de supprimer les "le, la, l', - et espace" il faut encore rajouter une règle pour certaines situations (comme celle-ci) et on en fini plus.
La meilleurs façon de faire et moins contraignante est d'utiliser celle du système sur lequel on travail.

Ta "logique" est la bonne mais ici on ne peut l'appliquer à 100% et il faut faire des compromis, ici c'est de les placer avant. (certains logiciels les placeront après ou en liste discontinue les intégrants à la suite en faisant abstraction de l'apostophe).

Comme tu peux le voir ici ou ailleurs le débat est infini et il n'a de sens à ce qu'on veut bien lui en donner.

**Comment by zack06007** [comment]
Tout à fait d'accord.Après le débat était de rendre la grille confortable à tous et logique ou ordonnée (au choix) selon l'avis de nous, utilisateur. J'ai croisé quelques liste et le C'est est bien classé à CE.
Après les exceptions comme "celle-ci" et cie ne pose pas de souci, vu que le symbole est en position finale. Ce qui est contraignant c'est quand l'accent est en seconde lettre faussant le classement.

Quand au CSS j'attends de voir la version javascript de la 2.1.5. Si ca me convient pas je l'integrerai (certainement que je te solliciterai pour te piquer quelques codes, ne sachant pas bien coder si ce n'est réagencer du C/C trouvé par ci, par là).

En tout cas, que Charlie ne se fasse pas de souci, si y a débat c'est que son travail interesse du monde, dont toi et moi, le surfeur.

**Comment by CaerCam** [comment]
Le débat est intéressant, mais très (trop ?) complexe je crois :

> « Après il faut déterminer un ordre, qui n'est "logique" qu'en fonction de la langue, la norme typo, et ici en l'occurrence informatique (jeux de caractère...) »

C'est _la_ grosse difficulté : le plugin est utilisé aussi bien par des européens/occidentaux que des orientaux ou des asiatiques ; j'ai connaissance de sites français, belges, espagnols, allemands, russes, ukrainiens, suédois, danois, croates, polonais, tchèques, thaïlandais, japonais, coréens, iraniens, qatari, brésiliens, argentins, chiliens… Cela donne une très grande variété de langues, d'alphabets et donc d'encodages différents, sans parler des serveurs pour lesquels la locale peut varier ; il est juste impossible de définir une norme qui convienne à tous, certaines langues présentant des spécificités uniques qui compliquent encore plus les choses…

Le système actuel est en réalité le choix du serveur, c'est un simple classement alphabétique lors de la requête à la base de données ; je ne connais pas précisément les règles, mais les modifier a obligatoirement pour conséquence d'alourdir les requêtes. Tant qu'on reste en encodage standard le classement est assez simple, mais dès qu'on commence à avoir des caractères exotiques, c'est beaucoup plus compliqué, quand ce n'est pas tout simplement impossible techniquement. 

Pour revenir sur l'exemple de l'apostrophe, qui n'est pas utilisée dans toutes les langues, ou pas avec la même fréquence ni les mêmes règle, appliquer un filtre de classement pour les « C' » ou « L' » n'aurait de sens qu'en français et en italien, pas en anglais ou en coréen. C'est je crois la limite du plugin : il permet de télécharger les données des films, offre un classement basique et plutôt uniforme quelle que soit la langue, mais dès lors qu'on veut y appliquer des normes précises de classement, cela devient du développement spécifique, inapplicable à l'ensemble du plugin.
