### ISSUE TITLE
Php Notices for using deprecated calls to WP_Widget

### ISSUE THREAD

**Issue by webstractions** [wpmovielibrary/wpmovielibrary#297]
Charlie,

Your `WPMOLY_Widget` class is showing Php Notices due to a deprecated constructor method. Your plugin is not the only one, there are literally hundreds affected by this method. The actual notice looks like this:

`
( ! ) Notice: The called constructor method for WP_Widget is <strong>deprecated</strong> since version 4.3.0! Use <pre>__construct()</pre> instead. in [...]\wp-includes\functions.php on line 3457
`

In `class-wpmoly-widget.php` inside of the `__construct` function there is the following line of code:

`
		$this->WP_Widget( $this->widget_id, $this->widget_name, $widget_args );
`

Changing to the following will rectify the situation:

`
		parent::__construct( $this->widget_id, $this->widget_name, $widget_args );
`

The statistics widget is not affected, BTW. In the file `class-statistics-widget.php` you are already using the proper constructor method.

**Comment by CaerCam** [comment]
Thanks Ronnie! Fixed on master.

**Comment by webstractions** [comment]
You're welcome Charlie!
