### ISSUE TITLE
Lack of visual indications in Movies Import section of Admin

### ISSUE THREAD

**Issue by webstractions** [wpmovielibrary/wpmovielibrary#298]
Charlie,

I went thru an import session in Admin for about 10 movies. After submitting a comma delimited list, the Imported Movies tab popped up as expected. I selected all movies and clicked the 'Get Metadata' bulk option. 

This is where I was wondering if anything was happening. There wasn't any 'graphical spinners' during this operation, nor was there a usual spinner in the browser tab. It just appeared to hang, or not be working at all. 

If you click on the Fetch Data icon one at a time, there is still no indication that it is working. However, depending on your internet connection speed, this is less trivial because results come back fairly quick. 

There is a synchronization issue with the top and bottom bulk action form. If you select a bulk action in the top form, it does not update the form on the bottom. And vice-versa. Plus after the bulk actions are completed, the two forms do not reset to the default 'Bulk Actions' selection. 

Of course the same indication problems exist inside of the Import Queue tab.  

Not tested, but noticed, there are not an accumulation of error notifications. I saw one notification for fetching metadata of a movie, but noticed that there were still three other movies that (apparently) failed to find metadata.

**Comment by lesurfeur** [comment]
J'ai l'impression que c'est le même problème soulevé dans le point 2 de cette issue : https://github.com/wpmovielibrary/wpmovielibrary/issues/289#issue-97322680

J'ai du mal à comprendre même avec un traducteur ce que soulève exactement webstractions.

**Comment by CaerCam** [comment]
Non, apparemment Ronnie ne voit pas s'afficher l'image de chargement des données, et il pointe quelques incohérences visuelles dans le comportement de l'importeur. Cette partie est complètement obsolète maintenant que je suis habitué à utiliser Backbone.js, j'attends d'avoir bouclé la version 2.1.5 pour pouvoir reprendre la 2.2 et la réécriture de l'importateur.

**Comment by CaerCam** [comment]
@webstractions Actually there _is_ a loading image that should appear to let you know the download process has started, for some reason I gather it's not showing for you. The inconsistencies you pointed are known of. That said, that part of the plugin is completely obsolete now that I got used to other technologies (Backbone.js) and will be completely rewritten in version 2.2. When I'm done with version 2.1.5 and the rewriting of the public movie grid to use JavaScript (and Backbone.js) I'll go back to 2.2 as soon as 2.1.5 is released :)

**Comment by webstractions** [comment]
Charlie, sounds good! Just wanted you to be aware of those things. Never really noticed until I did a bulk import of 10 films. Not sure why the loading image is not there on my installation, maybe a conflict somewhere. I will just sit tight for now, not a pressing issue.
