### ISSUE TITLE
custom archive for genres and movies of a genre

### ISSUE THREAD

**Issue by stargatehome** [wpmovielibrary/wpmovielibrary#300]
Hey Charlie,

is there a way to provide an own template for the genres archive and the archive of each genre with all the movies. Usually it uses the default template of the theme I guess.

Thanks for your help and cheers,

Mario

**Comment by webstractions** [comment]
Yep. This is a WordPress-centric type of thing. There is hierarchy for taxonomy templates (in this case 'genre'). The hierarchy is as follows:

1. taxonomy-{taxonomy}-{term}.php
2. taxonomy-{taxonomy}.php
3. taxonomy.php
4. archive.php
5. index.php

So for all genres, the template you need to create is `taxonomy-genre.php`. For more specific templates, 'drama' for example, it would be `taxonomy-genre-drama.php`.

With that said, creating templates for each genre is over kill. There is a way to do it programmatically by filtering the genre itself through the base `taxonomy-genre.php` file. 

For more info, check out WordPress Developer page for [Taxonomy Templates](https://developer.wordpress.org/themes/template-files-section/taxonomy-templates/)
