### ISSUE TITLE
Budget is meta details shows 0

### ISSUE THREAD

**Issue by abhijithmonu** [wpmovielibrary/wpmovielibrary#301]
I cannot able to remove BOX OFFICE tab nor i am getting budget info when i import the movie what should i do , i cannot leave BOX office tab blank please suggest!

**Comment by webstractions** [comment]
If the information is blank after an import, then there wasn't any data there to begin with. Suggest that you check the fields and fill in the blanks as needed. You can get additional info from site like IMDB and Wikipedia.

**Comment by abhijithmonu** [comment]
Can get AdSense approved by using this plugin????

**Comment by webstractions** [comment]
@abhijithmonu Is that a serious question? Suggest you check out the AdSense terms and figure it out on your own.
