### ISSUE TITLE
Forcer un résultat

### ISSUE THREAD

**Issue by ddeenniiss** [wpmovielibrary/wpmovielibrary#313]
Parfois une recherche renvoie un mauvais film, ce serait bien de pouvoir forcer un résultat. Par exemple, en faisant une recherche sur l'identifiant imdb à la place du titre.

Par exemple, une recherche sur "allô police" me renvoie http://www.imdb.com/title/tt0374173/ que je ne peux pas modifier. Hors, je cherche à encoder http://www.imdb.com/title/tt0258406/ ce qui n'est ps possible.

**Comment by ddeenniiss** [comment]
Et pour info, l'api semble répondre correctement http://www.omdbapi.com/?t=all%C3%B4+police&y=&plot=short&r=json

**Comment by zack06007** [comment]
Le codage ne se fait pas avec IMDB
Il utilise TMDB
Recherche déjà si ton film existe 
Dans le cas contraire tu peux créer la fiche sur le site

**Comment by ddeenniiss** [comment]
Oui désolé, je viens de me rendre compte que c'était pas IMDB mais TMDB.

**Comment by ddeenniiss** [comment]
Par contre, je pense que c'est super utile, p

**Comment by ddeenniiss** [comment]
Juste pour info, ce sera quelque chose de disponible dans la prochaine version ?

**Comment by CaerCam** [comment]
Absolument, ça l'est déjà avec la version 3.0-alpha1, une recherche avec `id:ttXXXXXXX` ou `id:XXXXXX` importe directement le film correspondant :)

**Comment by ddeenniiss** [comment]
Excellent, j'avais essayé mais sans le id:

Est-ce que ça marchera aussi avec TMDB ou tout passera par IMDB uniquement ?

Dans tout les cas, si c'est possible que cette fonction soit intégrée à l'import de films, id:ttxxxxx,id:ttxxxxx,... ça serait génial.

**Comment by CaerCam** [comment]
Non non, `id:XXXXXX` c'est pour TMDb, et `id:ttXXXXXXX` pour IMDb. Les deux sont supportés donc ;)

Et oui, ce sera ajouté à l'import multiple, bien sûr :)
