### ISSUE TITLE
Pas de résultats

### ISSUE THREAD

**Issue by ddeenniiss** [wpmovielibrary/wpmovielibrary#314]
J'ai beaucoup d'erreurs "Désolé, votre recherche n’a renvoyé aucun résultat. Essayez d’être plus précis ?" 

Je n'arrive pas à comprendre la logique mais ça arrive aussi pour des films où il n'y a pas de doutes possibles.

Par exemple, "Predchuvstviye" ne me montre pas la possibilité d'encoder http://www.imdb.com/title/tt0105163/

**Comment by ddeenniiss** [comment]
Pourtant l'api répond le bon résultat http://www.omdbapi.com/?t=Predchuvstviye&y=&plot=short&r=json

**Comment by zack06007** [comment]
Regarde sur TMDB si la fiche existe déjà.

**Comment by ddeenniiss** [comment]
J'essaie de mettre ici ce que je vois.

Pour un ajout simple, Il semble y avoir un problème avec les apostrophes qui ont besoin d'être échappées. Et certain films ne passe pas, exemple une recherche en anglais sur "Cochon qui s'en dédit" ou sur "Cochon qui s\'en dédit" alors que la fiche existe https://www.themoviedb.org/translate/movie/239460
