### ISSUE TITLE
Pagination give me a result page 404

### ISSUE THREAD

**Issue by edu-kart** [wpmovielibrary/wpmovielibrary#315]
Hi, First of all I want to thank you for this good plugin... Makes me easy a lot of things...

But, I'm having problems with my pagination... It takes me to a page 404 because it doesn't go to the correct URL. It goes to an address like this: http://mysite.com/grid/5:10/ASC/page/2

If I cut in the explorer "grid/5:10/ASC" it goes to the correct page....

I don't know how to fix it... I'd really apreciate your help....

In return of that, I could help you translating your plugin to Spanish....

I will wait for your answer soon... Thanks again...

**Comment by ddeenniiss** [comment]
I had same problem, it was resolved itself by adding movies

**Comment by edu-kart** [comment]
@ddeenniiss  I don't get it.... I added more and more movies, in fact I have more than 200 movies.... But, still pagination doesn't work....

**Comment by zack06007** [comment]
Pareil j'ai un souci quand je vais à une lettre quelconque, il me redirige toujours à ...grille/letter/6:12/title/ASC/ - soit toujours la même page du début.

Je viens de voir que la V3.0 va faire son entrée, j'ai hâte.
