### ISSUE TITLE
Movie Poster not showing since update to 2.1.4.2

### ISSUE THREAD

**Issue by Blutterbunged** [wpmovielibrary/wpmovielibrary#317]
I have just upgraded to WPML 2.1.4.2; now when I add a new movie, it searches the data from TMDB which works fine, and it shows the movie's poster in the 'Preview' tab; but when I then either 'Save as Draft' or 'Publish', the movie poster disappears (all other data and media work fine).

I also cannot seem to add a Poster manually (it shows up under the photos tax of the movie if I do that)

I have tried it in Safari, Firefox and Opera, and get the same result in all. Can this be fixed, or can I downgrade the plug-in to the previous version again?

thanks!

**Comment by CaerCam** [comment]
Version 2.1.x doesn't make it possible to manually upload posters, that was one of the main arguments in favor of rewriting the plugin in version 3.0…

Do the posters correctly download and then appear in the Featured Image metabox, not just in the preview?

**Comment by Blutterbunged** [comment]
Hi Charlie -

initially when it downloads the movie’s details from TMDB it does show the correct movie poster in the preview/summary tab (the one with the icon of a piece of film); it does not show in the Poster tab; but then once you save a draft or publish, the poster disappears from the preview/summary tab as well.

When I search for the movie on the tab with the clipboard icon, it finds it, downloads all data, gives the message ‘Done!’ and then a second later gives the message ‘Are you sure you want to do this?’ See screenshot:




if I click that it disappears; or if I ignore it it disappears after I have ‘saved', ‘published' or ‘updated' the movie.

All other data remains and is correct; the poster disappears when saving, publishing of updating.


You mention the Featured Image Metabox - I think that is supposed to be on the bottom right hand corner of the screen correct? I don’t get this box at all anymore. On the right hand I get the following boxes:
- Publish
- Categiories
- Tags
- Collections
- Genres
- Actors

and not Featured Image box.

I have not changed any settings in WP or WPML, nor have I updated my theme. The Featured Image box disappeared with the update to WPML 2.1.4.2.

Is there a way to downgrade back to the previous version of WPML so I can see if it is the WPML upgrade that causes this on my environment, or whether something else may have changed without me realising it?

thanks in advance for your help!

Bart

**Comment by Blutterbunged** [comment]
Hi Charlie -

you asked the right questions - it seems that somehow my Visual Composer plug-in had been deactivated - I turned it back on and now all works as it used to!

the featured image box is back, the metatags are correct again, and it saves the poster correctly :-)


thanks for your help!
Bart

**Comment by CaerCam** [comment]
Thanks for letting me know! Glad it's all back to normal :)
