### ISSUE TITLE
Metatags not working since update to 2.4.1.2

### ISSUE THREAD

**Issue by Blutterbunged** [wpmovielibrary/wpmovielibrary#318]
Besides my previous bug report of Missing Posters for new movies added to WPML, I noticed that all metatags seem to have disappeared? This causes significant issues with sharing movies/posts to Facebook and other media...

here is an example of a movie I added to WPML in an earlier version of the plug-in, which shows proper tagging on the Facebook scraper/debugger:
https://developers.facebook.com/tools/debug/og/object/?q=http%3A%2F%2Fblutterbunged.com%2Fmovies%2Froom%2F

and here is a movie I added with the latest version of WPML (2.4.1.2), which seems to have all meta tags missing, and as the Movie Poster is missing (see previous bug report) it picks up a poster from a random other movie:
https://developers.facebook.com/tools/debug/og/object/?q=http%3A%2F%2Fblutterbunged.com%2Fmovies%2F10-cloverfield-lane%2F

so as it is the updated plugin is not what I'd like to use - is it possible to downgrade? I tried downloading and installing an earlier version from Wordpress but that installation failed.

Can you help?

thanks!

**Comment by CaerCam** [comment]
Hi Blutterbunged,

Did you update other plugins/themes lately? WPMovieLibrary does not interact with META properties directly, that's more of a of theme field though some plugins use them too.

**Comment by Blutterbunged** [comment]
Hi Charlie - 

I have not updated my theme; I am not aware of any plug-in changes - last week I only updated WPML….

**Comment by Blutterbunged** [comment]
for completeness: all is working correctly again - seems that somehow my visual composer plug-in had been deactivated. turning that back on resolved all problems. Thanks Charlie!
