### ISSUE TITLE
Pas d'aperçu

### ISSUE THREAD

**Issue by ddeenniiss** [wpmovielibrary/wpmovielibrary#319]
L'aperçu renvoie vers une page d'erreur.

Dans la console Firebug:

NetworkError: 404 Not Found - http://dev.videoexpress.be/wp-content/plugins/wpmovielibrary-3.0-dev/public/css/wpmoly.css?ver=3.0" 
ReferenceError: s is not defined http://dev.videoexpress.be/wp-content/plugins/wpmovielibrary-3.0-dev/public/js/wpmoly.js?ver=3.0 ligne 4

Version 3.0 Alpha1

**Comment by CaerCam** [comment]
« Aperçu » dans le sens prévisualiser le post ? Si oui ce n'est pas anormal : l'alpha1 ne concerne pas la partie frontend, rien n'a encore été fait de ce côté, c'est l'objectif de l'alpha2 :)
