### ISSUE TITLE
Pas d'affiches ou de photos visibles

### ISSUE THREAD

**Issue by ddeenniiss** [wpmovielibrary/wpmovielibrary#320]
Quand on importe un film, les affiches ou les photos sont bien importées (elles ont présentes dans les affiches ou photos disponibles de la médiathèque) mais

Elles ne sont pas visibles dans le menu Affiches ou Images du film.
Importer des affiches permet de les voir mais pas de les importer (rien ne se passe)
Dans Images, il n'y a pas de menu "importer des images".

Le seul message d'erreur arrive quand on importe un film:

TypeError: message.map is not a function

http://dev.videoexpress.be/wp-content/plugins/wpmovielibrary-3.0-dev/public/js/wpmoly.js?ver=3.0 ligne 151

**Comment by ddeenniiss** [comment]
Version 3.0 Alpha1

**Comment by CaerCam** [comment]
Il y a eu quelques modifications en début de soirée sur cette partie (import d'images/affiches), est-ce que ça a changé quelque chose ?
