### ISSUE TITLE
The text on the tittle

### ISSUE THREAD

**Issue by lugorcorp** [wpmovielibrary/wpmovielibrary#322]
For some reason, the plugin is adding text to the page tittle, you can see an example here:
![bug](https://cloud.githubusercontent.com/assets/460179/14481175/1cbceb3e-00f6-11e6-8457-3bd194706a96.png)

This doesn't ocurre when the plugin is disabled.

Thanks.

**Comment by CaerCam** [comment]
Hi @lugorcorp,

Could you provide more details? Which version of the plugin, which theme/plugins installed could interact with it? On which page(s) does this happen?

**Comment by lugorcorp** [comment]
Which version of the plugin: The last one (2.1.4.2)
Which theme/plugins installed: Newspaper/10 plugins activated
Only happen on post section

could interact with it? That you mean, with the backend or front end?

**Comment by CaerCam** [comment]
The screenshot makes it impossible to see where exactly this is happening, so I'm not sure what could cause this. The Newspaper theme is premium which means I can't run tests on it. Is that site live?

**Comment by lugorcorp** [comment]
The site is in development, but yes, you can acces to the site: http://www.freakzone.xyz/

**Comment by lugorcorp** [comment]
Movie section: http://www.freakzone.xyz/peliculas/
You can see the error here: http://www.freakzone.xyz/category/tutoriales/

**Comment by CaerCam** [comment]
Thanks! Does this happen with another theme, or is it just Newspaper?
