### ISSUE TITLE
Making room for version 3.0

### ISSUE THREAD

**Issue by CaerCam** [wpmovielibrary/wpmovielibrary#323]
I just made some heavy cleaning on issues, closing about every issue remaining open and adding a "deprecated" label. There was a little less than a hundred open issues, some more than two years old; not much sense in keeping it this way.

Feel free to bump issues marked as deprecated if you need, that label (and closing) is only meant to free some space to focus on building version 3.0; when were done with that we can reopen tickets about feature requests and ideas :)

**Comment by stargatehome** [comment]
Great. :) Nice to see you working again on the Plugin.

**Comment by CaerCam** [comment]
@stargatehome I never stopped, really, it was just not publicly shared ;)

**Comment by alexbohariuc** [comment]
Hey,

When do you think you'll relesea 3.0? If you need any help, do tell.
