### ISSUE TITLE
MovieGrid: Links dont work

### ISSUE THREAD

**Issue by FilmjunkieGF** [wpmovielibrary/wpmovielibrary#325]
After the last update I get this problem:

http://demo.wpmovielibrary.com/movies/grid/letter/4:6/title/ASC/

As you can see when you want to sort for a letter it does not work (by clicking on the links). The link in the past was:
http://demo.wpmovielibrary.com/movies/grid/A/4:6/title/ASC/

I hope this can be fixed.

**Comment by zack06007** [comment]
Hello 
the solution: 
https://github.com/wpmovielibrary/wpmovielibrary/commit/23fecd8df5a971c337894e15d917e39d1a459563
😀

**Comment by CaerCam** [comment]
As speed-light-reply @zack06007 said, it can be fixed, and already has been fixed on the latest dev version :) Expect an update version 2.1.4.3 before the end of the week!
