### ISSUE TITLE
Cant Upload poster image

### ISSUE THREAD

**Issue by rajveer234** [wpmovielibrary/wpmovielibrary#362]
i cant upload poster image of any movie. poster image save bydefault plugin image no_poster-medium.jpg.

please resolved my problem. how can i import poster image.

Thanks.

**Comment by zack06007** [comment]
J'ai bien les affiches pour ma part mais...

Effectivement, on ne peut plus charger des nouvelles affiches via TMDB comme par le passé
Quand on clique sur nouvelle affiche il propose de les uploader via la touche PARCOURIR
Alors qu'avant il proposait toutes les affiches (multilangues) sur la fiche TMDB.

Sinon une belle et bonne année à toi 2018 Charlie!
