### ISSUE TITLE
Create single.php using wpmovielibrary data

### ISSUE THREAD

**Issue by docnzok** [wpmovielibrary/wpmovielibrary#364]
Is it possible to use the information that wpmovielibrary holds and create a single.php page where the headbox would show instead of the wordpress page where the post would be/

So when someone clicks on a post (which is actually a movie) I just want the cool headbox to show up and not the single.php that wordpress provides for the post.

**Comment by filipe-silva** [comment]
Hello using the following code inside the loop (I placed it in content.php) you get the headbox:
`<?php
$headbox = new WPMOLY_Headbox();
$headbox = $headbox->render( );
echo $headbox;
?>`

**Comment by meugamer** [comment]
Fala felipe beleza? Você consegue me passar o código que você usou no arquivo para proporcionar esse loop?
