### ISSUE TITLE
movie librarie stil supported ?need litle help

### ISSUE THREAD

**Issue by videoth** [wpmovielibrary/wpmovielibrary#367]
hi
am using movielibrarie 2.? with wp 4.3
its runing fine onley i wonder or its poseble to open my gategories in a grid to like my total collection shows nicly in a grid.
now my cato shows up in a list/datial view
i hope sameone can help mi and understands my question.
sorry for bad spelling!

greetz edward

**Comment by CaerCam** [comment]
Hi @videoth,

Yes, the plugin is still supported although I'm focusing on version 3, leaving version 2.x to bug fixes and minor features only.

Version 2.x does not support categories grids, but version 3 does! Plan is to have it release this autumn.
