### ISSUE TITLE
Issue looking up MetaData for movies

### ISSUE THREAD

**Issue by itroll42** [wpmovielibrary/wpmovielibrary#370]
I have setup my own API key for TMDB. And it was previously working, but recently I am unable to add any more movies into my collection. When trying to add a movie I go to the metadata tag as normal. Type in the movie title and search. It brings up a list of movie posters. When I click on a movie poster the posters disappear as normal, but nothing gets entered into the metadata.

When viewing the error console in the browser I see the following:

`wpmoly-editor-meta.js?ver=2.1.4.1:212 Uncaught TypeError: Cannot read property '_tmdb_id' of undefined
    at Object.success (wpmoly-editor-meta.js?ver=2.1.4.1:212)
    at i (load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,underscore,backbone,utils,jquery-ui-widget,j…:2)
    at Object.fireWith [as resolveWith] (load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,underscore,backbone,utils,jquery-ui-widget,j…:2)
    at y (load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,underscore,backbone,utils,jquery-ui-widget,j…:4)
    at XMLHttpRequest.c (load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,underscore,backbone,utils,jquery-ui-widget,j…:4)
success	@	wpmoly-editor-meta.js?ver=2.1.4.1:212
i	@	load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,underscore,backbone,utils,jquery-ui-widget,j…:2
fireWith	@	load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,underscore,backbone,utils,jquery-ui-widget,j…:2
y	@	load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,underscore,backbone,utils,jquery-ui-widget,j…:4
c	@	load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,underscore,backbone,utils,jquery-ui-widget,j…:4`

The error is that on line 212 response coming back is

`“<h1>Error thrown</h1><p>[] operator not supported for strings</p>”`

The problem appears to be that when this gets called

`wp-admin/admin-ajax.php?action=wpmoly_search_movie&nonce=f54068a915&type=id&data=91314&lang=en`

its returning a web page that says error thrown. []operator not supported for strings.

So how can debug this issue? I’ve disabled all the newer plug-ins that were installed recently in wordpress. To go back to what it was when i remember this last working. and that didn’t help.

The only other thing that changed was wordpress got updated to WP 4.7.4

**Comment by CaerCam** [comment]
Thanks a lot for reporting this! I've been aware of that bug for months without any clue to reproduce it, turns out it comes from PHP 7.1 and bad coding practice. Should be fixed now!
