### ISSUE TITLE
Director not imported

### ISSUE THREAD

**Issue by itised-83** [wpmovielibrary/wpmovielibrary#372]
Hi,
starting from a few days, import process doesn’t retrieve director name. Here’s some screens:

http://picpaste.com/pics/6b00c06b62a2d9a970a3a65594ec382a.1495017176.jpg
http://picpaste.com/pics/fae7c8ae4160c73b613976ec3cd9a42b.1495017209.jpg
http://picpaste.com/pics/1a28aba4b6c3e4e4e13ea30bea4ef2b4.1495017230.jpg

Is it a bug or something wrong with the TMDB api? Thanks

**Comment by zack06007** [comment]
I have same problem since last update

**Comment by CaerCam** [comment]
Fixed along with #371 by 4ffecd98690ef1a6f2a237cb6c58116f8e1dfa53.

**Comment by itised-83** [comment]
It works, thanks.

**Comment by CaerCam** [comment]
You're welcome, thanks for reporting!

Pushing update on WP.org right now.
