### ISSUE TITLE
Broken Movies manager screen (admin)

### ISSUE THREAD

**Issue by bahadircolak** [wpmovielibrary/wpmovielibrary#374]
Movies (admin) screen is broken. I've disabled other plugins but still no luck. What can cause this?

![izlevadmin](https://user-images.githubusercontent.com/480071/28208926-e4316f0e-6898-11e7-87d8-20a2416fd457.png)

**Comment by CaerCam** [comment]
Hi @bahadircolak,

That's a weird one. This still happens once you disabled all other plugins, right? Did you try hiding some columns in the screen options?

**Comment by bahadircolak** [comment]
I think scripts are broken somehow. Screen options link doesn't work either. I still can manage using Your movies section but I don't know what to do when I add a lot of content.

**Comment by meugamer** [comment]
As it happened the same after I created a page and a category for the movies.
