### ISSUE TITLE
Can't import movie, debug info inside

### ISSUE THREAD

**Issue by roig** [wpmovielibrary/wpmovielibrary#375]
Today I can't import movies It gives me this error:

`TypeError: response.data is undefined
[Més informació]  wpmoly-importer-meta.js:130:1
	success http://www.XXXX.cat/wp-content/plugins/wpmovielibrary/assets/js/admin/wpmoly-importer-meta.js:130:1
	i http://www.XXXX.cat/wp-admin/load-scripts.php:2:27444
	fireWith http://www.XXXX.cat/wp-admin/load-scripts.php:2:28213
	y http://www.XXXX.cat/wp-admin/load-scripts.php:4:22719
	c http://www.XXXX.cat/wp-admin/load-scripts.php:4:26925`

The $response variable returns with this error:
`
"API Error: server connection to "http://tmdb.caercam.org/api/search/movie/interstellar/ca" returned error 500: Internal Server Error"`

**Comment by roig** [comment]
@CaerCam 
The $response variable returns with this error:
`
"API Error: server connection to "http://tmdb.caercam.org/api/search/movie/interstellar/ca" returned error 500: Internal Server Error"`

**Comment by CaerCam** [comment]
Hi @roig, that's actually the same issue reported in #376, SSL certificate validation error when using the default API. Only default API is affected, using your own API key prevents this bug from showing up. Should be fixed now.

Regardless, it's always a good idea to get your own API key, you might to consider applying for one :)

Thanks for reporting this!
