### ISSUE TITLE
Not loading the movies when adding a new movie.

### ISSUE THREAD

**Issue by Misstomboy** [wpmovielibrary/wpmovielibrary#376]
I updated to 4.8 on WordPress and now your plugin won't let me add new movies at all and I need to finish this and can not.

**Comment by Misstomboy** [comment]
Ok Issues with meta data being loaded was with your api. Because I used my own api and now works perfect. I solved my issue but for other you may want to check on the api and why it is not working.

**Comment by Misstomboy** [comment]
Ok after hours of testing to see if it was the API I found out it was really API with https. So basically I was on HTTP and was trying to fetch by https why I have no clue. But I now fixed my site it is now https and can not fetch the meta data with no problem from your API but I still going to use mine. So consider this solved.

**Comment by CaerCam** [comment]
Thanks for you insight @Misstomboy! This indeed comes from using the default API which resulted in some SSL certificate validation error. Should be fixed now.
