### ISSUE TITLE
Bug on import existing movie

### ISSUE THREAD

**Issue by Antera** [wpmovielibrary/wpmovielibrary#378]
Hello,

An error I found while importing :

Import movies

Tab 3 “Import new movies”, type : “Equalizer” (without “”)
Then Tab 1 “Imported movies”, click Icon Fetch data from Imdb, select “The Equalizer” movie, and click “+”
Then Tab 3 “Import new movies”, type : “The Equalizer” (=meta title found by fetch data and added to import queue)

= Javascript error
TypeError: Cannot read property ‘length’ of undefined
/wp-content/plugins/wpmovielibrary/assets/js/admin/wpmoly-importer-movies.js?ver=2.1.4.5:109

Please note the subtile difference (in tab 3 “Import new movies”) : we can still write “Equalizer” , but we cannot type “The Equalizer” = name of a movie confirmed by import

Thanks for the plugin
Kind regards

**Comment by CaerCam** [comment]
Should be fixed by 256628a6118f4a03ee2952dfc7cd4aaff167fecb!

**Comment by Antera** [comment]
Hehe good, now we have a message "Movie The Equalizer already imported" :-)
