### ISSUE TITLE
Error in Achives settings : Grid Movies meta

### ISSUE THREAD

**Issue by Antera** [wpmovielibrary/wpmovielibrary#379]
Hello,

Many thanks for this plugin, it’s very good.
One error, I tried in 2 different installs :

Movies > Settings > Archives > Movies archives
Grid Movies Meta
Here I cannot drag & drop the values from “Available” to “Used” (Title, Year, Rating)

Google Chrome Javascript error :
TypeError: Cannot read property ‘find’ of undefined
/wp-content/plugins/wpmovielibrary/includes/framework/redux/ReduxCore/inc/fields/sorter/field_sorter.min.js?ver=1505073896:1

**Comment by Antera** [comment]
Hi @CaerCam ,

Thanks for your prompt response
I updated the plugin to the last version
I don't see the JS error anymore
But still unable to drag and drop those options to the left

**Comment by cineasiefr** [comment]
Hello, 
I don't see the JS Error, but like @Antera , I can't drag and drop those options to the left :(

Maybe i need to install the V3 version ?
