### ISSUE TITLE
Use the plugin as a "Already seen / To be seen" list

### ISSUE THREAD

**Issue by Antera** [wpmovielibrary/wpmovielibrary#381]
Hello,

I had a list of movies in a text file : 

==Movies To see==
Movie 1 (John recommended this movie)
Movie 2 (critics say : best horror movie of all time)
...

==Movies Seen==
Movie 3 (what a joke, lost 2 hours of my life)
Movie 4 (best manga ever)
...

I replaced it by http://movies.neosama.com

What could I use to separate Movies "Seen" and "To see" ?

Collections and Genres : too many already, don't want to add "Seen" and "To see" in those lists
Metadata : let's keep this automatic

Idea 1 : Details : "movie status" field looks good but should rename the options ?
Idea 2 : Movie rating : could use this. Not rated = to see, rated = seen ?
Idea 3 : activate taxonomy WP categories on Movies and create categories "To see" and "Seen" ?
Idea 4 : add a custom field to Movies ?

What do you think is the best option to work well with the plugin and easy to use ?

Many thanks for your insights

_This is a not a bug report, this is an advice/support message._

**Comment by CaerCam** [comment]
Personally, I'd go with a couple of collections, but if you're not going with this one, ratings would be my second choice; it makes sense that an unrated movie is a movie you've not seen yet :)
