### ISSUE TITLE
How To install the plugin on CMS Datalife Engine?

### ISSUE THREAD

**Issue by veronicaginger** [wpmovielibrary/wpmovielibrary#382]
Hello. i check the documentation and found the installation in Wordpress.
can i install this wpmovielibrary on Datalife Engine? if this possible can you tell me how to do that?

thank you.

**Comment by CaerCam** [comment]
Hi @veronicaginger,

Long story short, no. The plugin is design for WordPress and uses internal WordPress features, no chance to make it work with another CMS, sorry!
