### ISSUE TITLE
Mises à jour

### ISSUE THREAD

**Issue by chris241182** [wpmovielibrary/wpmovielibrary#386]
Salut Charlie,
Je suis actuellement en train de créer un site de cinéma bis et je découvre ton plugin qui va me faire gagner pas mal de temps.
Je bosse actuellement sur la dernière version stable et j'ai testé la 3 avec les grilles bien sympathiques !!!
Quand la 3 sortira, sera-t-il possible de mettre à jour sans problème ma version vers la 3 ou faudra-t-il tout recommencer ?
Merci beaucoup !
Chris

**Comment by CaerCam** [comment]
Bonjour @chris241182,

Pas de soucis normalement pour un passage à la version 3, il n'y a pas de changement dans la façon dont sont traitées les données, en revanche il s'agit d'une réécriture complète du plugin, donc une grande partie des fonctionnalités « visibles » (grilles, en-têtes, shortcodes, etc) va (beaucoup) changer… Il y aura sans doute au minimum quelques ajustements nécessaires, tout dépend du niveau d'imbrication du plugin dans votre site :)
