### ISSUE TITLE
Not sure where to post this -- if I want some customization done, who would I ask?

### ISSUE THREAD

**Issue by ploom100** [wpmovielibrary/wpmovielibrary#387]
Looking to get some customization for this PlugIn  -- I'd pay for it.   Obviously someone who is familiar with the plugin.  Where would I go?

**Comment by CaerCam** [comment]
Hi @ploom100,

You would probably drop me an email at charlie@caercam.org with some details about you project, budget and deadline, see what we can do for you :)
