### ISSUE TITLE
wpmolicon

### ISSUE THREAD

**Issue by nodeth** [wpmovielibrary/wpmovielibrary#388]
My problem is that in every wp_movie_plugin page I can't see any icon,
only anonymous squares. How can I solve it?
I've tried uninstall and reinstall, manually upload assets/css and assets/fonts
but nothing.
IMHO the problem is out of the plugin... but where?

**Comment by CaerCam** [comment]
Hi @nodeth,

That's not unheard of; sometimes removing the gibberish URL suffix seems to fix it. See the [font style.css file](https://github.com/wpmovielibrary/wpmovielibrary/blob/master/assets/fonts/wpmovielibrary/style.css) and remove the `?-rnqd04` from each URL, see if icons show.

**Comment by nodeth** [comment]
It's OK.
Thank you very much!
