### ISSUE TITLE
Look for IMDB movie with more than 20 results for the title

### ISSUE THREAD

**Issue by ADAGEBF** [wpmovielibrary/wpmovielibrary#393]
Bonjour et merci pour ce super plugin que je découvre. 
J'ai commencé l'importation de mes 3000 films, parmi lesquels The River (La Femme au corbeau, Franck Borzage, 1928) : http://www.imdb.com/title/tt0020335/
Malheureusement ce film n'apprait pas dans les 20 premiers résultats de la recherche IMDB, et je ne peux donc pas en importer les metadonnées. 
Comment puis-je étendre les résultats à 30 ou 40 pour être sûr d'y trouver le film recherché ?
Merci.

**Comment by zack06007** [comment]
Bonjour 

Tout d'abord le site sur lequel il recherche est Tmdb et non imdb. Verifies donc que le film y est bien, j'ai vite fait une recherche et j'ai rien trouvé. 

Il te reste sinon à créer le film sur Tmdb et ensuite relancer la recherche, je l'ai fais pour des films nouveaux ou méconnus.

**Comment by zack06007** [comment]
À priori il y est: https://www.themoviedb.org/movie/110736-the-river

Sinon Essayes par numéro de référence ou Real... j'ai pas de pc sous la main pour faire un test

**Comment by ADAGEBF** [comment]
Merci pour ce retour rapide. 
J'ai essayé par référence et réal sans succès, il faut que la recherche soit une expression exacte du titre pour que ça foncitonne. 
J'ai l'impression que le seul moyen serait donc d'étendre le nombre de résultats à + de 20. J'ai trouvé le fichier wpmovielibrary\assets\js\admin\wpmoly-importer-movies.js mais n'y vois pas de nombre 20...
Merci encore.

**Comment by zack06007** [comment]
Il n'y avait pas de traduction française sur tmdb!
Ça va te sauver sur ce coup, cela n'empêche que si y avait que the River je n'aurai pas eu de solution 

Donc pour le moment je suis aller sur tmdb et j'ai renseigné le titre FR. Tu devrais pouvoir arriver à trouver le titre par son titre FR. (Le temps que la bdd l'ai pris en charge) 

Tiens-nous au courant ça fonctionnera c'est sur

**Comment by ADAGEBF** [comment]
Effectivement ça a marché, merci beaucoup !

**Comment by ADAGEBF** [comment]
Par contre du coup j'ai le même problème sur le film L'Argent, de Robert Bresson : https://www.themoviedb.org/movie/42112-l-argent

**Comment by CaerCam** [comment]
On ne peut pas changer le nombre de résultats renvoyés par l'API, seulement parcourir les pages de résultats ; le plugin ne gère pas ça et ce serait trop compliqué à mettre en place proprement en l'état.

En revanche, si le film a bien une fiche TMDb, on peut copier l'ID (qu'on retrouve dans l'URL, par exemple **42112** dans https://www.themoviedb.org/movie/42112-l-argent) et le coller dans le champ de recherche de l'éditeur de films en sélectionnant « TMDb ID » à la place de « Titre du film ». C'est un peu sale, mais ça devrait fonctionner : https://gist.github.com/CaerCam/d89764f06c3e9a9676a7c5b0af702cc6

**Comment by ADAGEBF** [comment]
Bonjour et merci,
Effectivement, cette solution devrait me convenir, dans la mesure où je ne rencontre ce problème que pour moins d'un pourcent des films. 
Je suis dans une fiche film > WordPress Movie Library > Métadonnées, mais n'y vois pas où sélectionner "TMDb ID" ? 
Merci.

**Comment by CaerCam** [comment]
Le sélecteur devrait apparaître au même niveau que la liste déroulante des langues et le champ de recherche :
![screenshot-2017-12-4 editer un film d3v wpmovielibrary com wordpress](https://user-images.githubusercontent.com/621662/33532609-5154b902-d89b-11e7-9362-79ae8a8f9431.png)

Ce n'est pas le cas ?

**Comment by ADAGEBF** [comment]
Ah non, effectivement, je n'ai pas ce sélecteur ! 
WP et plugin à jour, thème twenty seventeen, aucun autre plugin à part akismet...

**Comment by CaerCam** [comment]
Ah, c'est étrange, ça. Le fichier `wpmoly-edit-movies.css` a bien été mis à jour, cache vidé ?

**Comment by ADAGEBF** [comment]
C'est une fresh install. 
Essayé sur Firefox et Chrome, cache vidé. Aucun effet...

**Comment by CaerCam** [comment]
Je viens de tester sur une install toute neuve, https://gist.github.com/CaerCam/d89764f06c3e9a9676a7c5b0af702cc6 a correctement rendu le sélecteur visible. Vous n'avez pas eu d'erreur en appliquant le patch je suppose ?

**Comment by ADAGEBF** [comment]
Ah non, j'ignorais jusqu'à l'existence de ce patch ; où puis-je trouver de la documentation sur le sujet ?

**Comment by CaerCam** [comment]
C'est un patch git tout simple, à télécharger dans le répertoire principal du plugin et à appliquer grâce à la commande [`git apply`](https://git-scm.com/docs/git-apply), en l'occurrence `git apply fix_tmdb_id_search.patch`.

Si vous n'utilisez pas git, c'est moins pratique, mais vous pouvez éditer les fichiers à la main pour appliquer les changements manuellement.

**Comment by ADAGEBF** [comment]
Ah oui effectivement, je n'avais pas compris. N'utilisant pas git je vais tenter à la main. 
Merci.

**Comment by ADAGEBF** [comment]
Désolé de réouvrir encore une fois ce ticket, mais il semble que depuis l'application du patch la récupération des métadonnées via l'outil d'importation semble ne plus foncitonner.

**Comment by zack06007** [comment]
Rend service à tmbd en renseignant les traductions françaises ainsi tu peux retrouver ton film comme on l'a fait pour la femme au corbeau.

A savoir que c'est à la marge normalement tout est bien indiqué ... Faudra que tu partages ton site pour voir tes références cinéphiles!

**Comment by ADAGEBF** [comment]
Bonjour zack06007,
En fait j'aurais peut-être du créer un autre ticket, mais depuis l'application du patch de CaerCam l'importation des métadonnées via l'outil d'importation ne fonctionne plus du tout, que ce soit pour des films dont l'outil trouve la correspondance directement, ou pour ceux dont on sélectionne l'affiche après avoir obtenu plusieurs résultats de recherche dans un premier temps.

**Comment by zack06007** [comment]
Niveau programmation je ne sais pas 
Si tu as pas trop avancé désinstalles et reinstalle le plugin ou attend un autre conseil 

Si sur 3000 tu as 10 titres non traduits le faire sur tmdb est rapide et ça rend toujours service au suivant 

Désolé de pas pouvoir plus t'aider

**Comment by ADAGEBF** [comment]
Ici le problème n'est plus les films non traduits, mais bien ceux dont la traduction du titre est aussi trop banale. Exemple le film de Bresson nommé L'Argent, en Anglais The Money, qui sont des titres trop communs pour ne pas figurer dans le top 20 des titres sortis dans la recherche. D'où la nécessité d'utiliser la recherche par ID, qui fonctionne très bien - et pour laquelle je remercie encore CaerCam - mais dont le patch fait planter l'importation de masse. 
Merci.

**Comment by zack06007** [comment]
J'avais bien compris le problème ;)

**Comment by CaerCam** [comment]
J'ai légèrement modifié le fonctionnement de la recherche par ID : le sélecteur reste masqué, mais on peut préciser un ID en recherchant `id:12345` à la place du titre du film. Ce changement ne concerne que l'éditeur de films, pas l'import groupé. Les tests sont les bienvenus :)

**Comment by zack06007** [comment]
Je reste ça dès que je suis devant mon PC 
Je te tiens au courant d'ici peu
