### ISSUE TITLE
Github plugin vs wp.org one 

### ISSUE THREAD

**Issue by MaximeCulea** [wpmovielibrary/wpmovielibrary#394]
Hi there,

First of all, good job with your plugin.

Wanted to warn you that when downloading the plugin from Github, I have a JS error while searching movies.
![capture d ecran 2017-12-15 a 17 40 51](https://user-images.githubusercontent.com/5576409/34051569-5e370724-e1bf-11e7-9605-da020d51573f.png)

I have fixed my issue by downloading it on wp.org. Is there a difference between these 2 ?

**Comment by ranjithsiji** [comment]
The one in github is 3.0 WIP and the plugin in wp.org is the stable version 2.

**Comment by MaximeCulea** [comment]
@ranjithsiji so it explains the errors ?
