### ISSUE TITLE
Stuck in searching

### ISSUE THREAD

**Issue by StratosKampourogiannis** [wpmovielibrary/wpmovielibrary#395]
I have installed the plugin and i am trying a movie to test it out but when i enter the movie name and click on search it gives me a message "searching movie" but it doesn't do anything. It stays like this forever.

Am i missing something?

**Comment by cineasiefr** [comment]
Hello, Strange. Do you try with Terminator or another blockbuster movies ? 
Because, your movie need to exist on TMDB
