### ISSUE TITLE
Query Slow 

### ISSUE THREAD

**Issue by misterdokin** [wpmovielibrary/wpmovielibrary#396]
Hi.
Congratulation with this awesome plugin...You are the Best!:-D
Lately, I noticed a great slowdown of the site that sometimes led to the blockade of the site. report following, using query queries, queries that slow down the site a lot.

SELECT DISTINCT meta_value FROM wp_postmeta WHERE meta_key LIKE '_wpmoly_movie_release_date' ORDER BY meta_value | +WPMOLY_Utils::get_used_meta()wp-content/plugins/wpmovielibrary/includes/classes/class-wpmoly-utils.php:1114 | Plugin: wpmovielibrary | 1354 | 0,0807
-- | -- | -- | -- | --
SELECT meta_value FROM wp_postmeta WHERE meta_key LIKE '_wpmoly_movie_spoken_languages' ORDER BY meta_value | +WPMOLY_Utils::get_used_meta()wp-content/plugins/wpmovielibrary/includes/classes/class-wpmoly-utils.php:1114 | Plugin: wpmovielibrary | 1611 | 0,0736
SELECT meta_value FROM wp_postmeta WHERE meta_key LIKE '_wpmoly_movie_production_companies' ORDER BY meta_value | +WPMOLY_Utils::get_used_meta()wp-content/plugins/wpmovielibrary/includes/classes/class-wpmoly-utils.php:1114 | Plugin: wpmovielibrary | 1611 | 0,0722
SELECT meta_value FROM wp_postmeta WHERE meta_key LIKE '_wpmoly_movie_production_countries' ORDER BY meta_value | +WPMOLY_Utils::get_used_meta()wp-content/plugins/wpmovielibrary/includes/classes/class-wpmoly-utils.php:1114 | Plugin: wpmovielibrary | 1611 | 0,0734
SELECT meta_value FROM wp_postmeta WHERE meta_key LIKE '_wpmoly_movie_certification' ORDER BY meta_value | +WPMOLY_Utils::get_used_meta()wp-content/plugins/wpmovielibrary/includes/classes/class-wpmoly-utils.php:1114 | Plugin: wpmovielibrary | 1611 | 0,0733

how can I solve this problem? it causes me continuous blocks both on backend and frontend
Many thanks and congratulations for your excellent work

**Comment by Rahe** [comment]
Hello,

I had the exact same problem, I replaced the LIKE by a "=" and the queries drop to 0,00005 sec on file includes/classes/class-wpmoly-utils.php:1116

Rahe,

**Comment by misterdokin** [comment]
Hi
could you explain to me step by step how to make this change?

**Comment by misterdokin** [comment]
I attach the PHP file that create query slow 
[class-wpmoly-utils.zip](https://github.com/wpmovielibrary/wpmovielibrary/files/1652769/class-wpmoly-utils.zip)

**Comment by Rahe** [comment]
Replace 
```				 WHERE meta_key LIKE '_wpmoly_movie_{$meta}'```
By 
```				 WHERE meta_key = '_wpmoly_movie_{$meta}'```
in https://github.com/wpmovielibrary/wpmovielibrary/blob/master/includes/classes/class-wpmoly-utils.php#L1114

**Comment by misterdokin** [comment]
Awesome...Thanks you very much!
