### ISSUE TITLE
url archive pagination errors

### ISSUE THREAD

**Issue by cedricARN** [wpmovielibrary/wpmovielibrary#402]
hello,
les urls sur les ages d'archives du plugin ne fonctionnent pas:
exemple grille en 3x9 en dessous j'ai les pages suivantes : 
1 2 3 Suivant »
/grille/4:6/DESC/page/2 ne fonctionne pas à la place fonctionne : /page/2
/grille/4:6/DESC/page/3 ne fonctionne pas à la place fonctionne : /page/3

**Comment by cedricARN** [comment]
I'm replacing : 
line 23 : 		<li><a href="<?php echo $link['url']; ?>" class="<?php echo $link['class']; ?>"><?php echo $link['title']; ?></a></li>
in file : wpmovielibrary\views\archives\pagination.php
by : 
<li><a href="<?php $link['url'] = str_replace("/grille/4:6/DESC","",$link['url']); echo $link['url'];?>" class="<?php echo $link['class']; ?>"><?php echo $link['title']; ?></a></li>

**Comment by cedricARN** [comment]
think there is a better way too

**Comment by cineasiefr** [comment]
Salut, est-ce que tu as changé la taxonomie ? De mon coté ça plantait quand j'avais changé la taxonomie...j'ai restauré le nom d'origine...petit tour dans la partie des permaliens et hop magie tout marchait de nouveau

**Comment by cedricARN** [comment]
tu tu as mis quoi en permaliens ?

**Comment by cineasiefr** [comment]
rien, tu vas dans la rubrique parmalien et tu sauvegarde sans rien changer... normalement ca fait un "update" du truc.
