### ISSUE TITLE
Main page other than Home Page

### ISSUE THREAD

**Issue by jmatdrama** [wpmovielibrary/wpmovielibrary#406]
I need to assign WP Movie Library to a page other than Home Page. Under Settings: General: Show Movies in Home Page - I chose DISABLED. However now my "Movies/TV" page http://www.jeanniemusick.com/my-reviews/film-tv/ comes up with a choice dropdown which leads to the breakout pages http://www.jeanniemusick.com/collection/vampire-humorous/ as per your example http://demo.wpmovielibrary.com/movies/the-dark-knight/ except mine runs continuous. I want that page to be like your example http://demo.wpmovielibrary.com/page/2/ which shows just the poster and description, 2 columns which can be clicked on to get the detail page. How can I change it so it looks like yours?

**Comment by Gunnar-GO** [comment]
If i read the call correctly you should check the used fonts maybe it was overload or is blocked. The icons come from a special Font that is delvered with the plugin.
