### ISSUE TITLE
Icons gone from admin

### ISSUE THREAD

**Issue by Gabor851** [wpmovielibrary/wpmovielibrary#407]
Hello

I am using the plugin on more sites, but from one the icons are gone and I have no idea what happened. I tried to delete and install the plugin, but I still do not have icons in the admin area for this plugin.

![image](https://user-images.githubusercontent.com/38889620/39483047-7372d082-4d71-11e8-8806-5ac1732756f0.png)

Thank you for an idea

**Comment by Gunnar-GO** [comment]
If a read the call correctly you should check the used fonts. maybe it was overload or blocked (check the filerights too). The missing icons are from a special font, that is delivered with the plugin.
