### ISSUE TITLE
Settings are not saved

### ISSUE THREAD

**Issue by psycholyzern** [wpmovielibrary/wpmovielibrary#410]
In Settings, even after pressing save and a notification says "Settings saved" shows up, the settings are not saved. You can reproduce by reloading the page after saving the settings.

Also Movies are not showing up in Homepage even the toggle is on.

I uninstalled the old version and installed beta 3.0.0, so I believe I am doing it correct?

**Comment by meugamer** [comment]
You should not even use the plugin in the production environment, but in the test environment. Some functions are still not working.

**Comment by psycholyzern** [comment]
I run a small blog and barely got visitors😂.
I wouldn't mind testing the plugin.
Since the blog post asking users to report bugs, I did.

**Comment by meugamer** [comment]
Yes! You are right! It is good that this happens. But it is worth mentioning that the same mentioned that to test the new plugin is in the version of php 7.2. To work properly.

**Comment by psycholyzern** [comment]
Yes. I am using php 7.2 per requirement, with nginx.
There is no error either in server log or browser console. So I couldn't help much other than hoping the dev can reproduce the issue.

**Comment by CaerCam** [comment]
Nice catch @psycholyzern. Seems settings are correctly saved, but toggle field values are properly handling and get confused with the field default value. It should be fixed by the next commit.
