### ISSUE TITLE
incomplete install?

### ISSUE THREAD

**Issue by Elaine501** [wpmovielibrary/wpmovielibrary#411]
I installed the beta and WP said that it was activated, however when I click on any of the links under Movie Library I get a blank screen in the dashboard area.

**Comment by CaerCam** [comment]
Hi @Elaine501,
Blank screen usually means PHP error. Anything on the server's error log? Which versions of PHP and WordPress are you running?

**Comment by Elaine501** [comment]
Needed to add this : Can see sidebar and top bar on WP dashboard.

 

PHP is 7.1 and current WP

 

 

 

Elaine Hodges

 <http://classicmovietreasures.com/> Classic Movie Treasures

 

 <https://twitter.com/CMovieTreasures> Twitter |  <https://www.facebook.com/groups/ClassicMovieTreasures/> Facebook |  <https://www.pinterest.com/classicmovietre/> Pinterest |  <https://www.instagram.com/classicmovietreasures/> Instagram

**Comment by CaerCam** [comment]
Ok, so probably a JavaScript issue. Can you see any sign of error in the [browser console](https://developer.mozilla.org/en-US/docs/Tools/Browser_Console)?

**Comment by Elaine501** [comment]
[Show/hide message details.] TypeError: wp.api.models.Movies is undefined api.js:50:3

<anonymous>

https://classicmovietreasures.com/wp-content/plugins/wpmovielibrary-3.0.0-beta/public/assets/js/api.js:50:3

i

https://classicmovietreasures.com/wp-admin/load-scripts.php:2:27444

add

https://classicmovietreasures.com/wp-admin/load-scripts.php:2:27748

<anonymous>

https://classicmovietreasures.com/wp-content/plugins/wpmovielibrary-3.0.0-beta/public/assets/js/api.js:49:2

<anonymous>

https://classicmovietreasures.com/wp-content/plugins/wpmovielibrary-3.0.0-beta/public/assets/js/api.js:22:2

JQMIGRATE: Migrate is installed, version 1.4.1 load-scripts.php:9:542

[toasts]: running! toasts.min.js:1:4040

[wpmovielibrary]: Run Forrest, run! wpmoly.js:282:3

[Show/hide message details.] TypeError: wp.api.models.Movies is undefined api.js:50:3

<anonymous>

https://classicmovietreasures.com/wp-content/plugins/wpmovielibrary-3.0.0-beta/public/assets/js/api.js:50:3

i

https://classicmovietreasures.com/wp-admin/load-scripts.php:2:27444

add

https://classicmovietreasures.com/wp-admin/load-scripts.php:2:27748

<anonymous>

https://classicmovietreasures.com/wp-content/plugins/wpmovielibrary-3.0.0-beta/public/assets/js/api.js:49:2

<anonymous>

https://classicmovietreasures.com/wp-content/plugins/wpmovielibrary-3.0.0-beta/public/assets/js/api.js:22:2

 

 

Elaine Hodges

 <http://classicmovietreasures.com/> Classic Movie Treasures

 

 <https://twitter.com/CMovieTreasures> Twitter |  <https://www.facebook.com/groups/ClassicMovieTreasures/> Facebook |  <https://www.pinterest.com/classicmovietre/> Pinterest |  <https://www.instagram.com/classicmovietreasures/> Instagram
