### ISSUE TITLE
About templates.

### ISSUE THREAD

**Issue by meugamer** [wpmovielibrary/wpmovielibrary#412]
I spent some time studying how you separated the theme for Allocine, imdb and the pattern. I started to separate and created one based on the imdb templates. I think it would be interesting to add a default template so that the person can follow his own in version 3.0 .. What do you think of this addition?

**Comment by CaerCam** [comment]
Hi @meugamer,

Something like a boilerplate template to allow basic theming?

**Comment by meugamer** [comment]
Currently I've set up a layout this way. And use the post-> id of the term taxonomy to pull as images of the actors automatically. The same can be any scheme used as taxonomy and the main data of wpmovie. Soon if there is a layout or an application that can be included in your movie layout. It would be interesting!
![image](https://user-images.githubusercontent.com/31143546/44960533-cb7d7a80-aed7-11e8-93b2-b8a147d72692.png)
