### ISSUE TITLE
After installation

### ISSUE THREAD

**Issue by kebekois** [wpmovielibrary/wpmovielibrary#413]
White pages after installation 
`https://www.kebekois.com/Sanstitre.png`

**Comment by CaerCam** [comment]
Same issue #411. Did you by any change notice some error in the browser console?

**Comment by meugamer** [comment]
See the video that shows the result in white.
. https://videopress.com/v/LqrG85OW

**Comment by CaerCam** [comment]
Thanks, definitely JavaScript issue. Try enabling WordPress's debug mode and script debug, and take a look at the JavaScript console on any page that doesn't work. There should some indication as to what's going on here.

**Comment by meugamer** [comment]
404 /wp-json/wpmoly/v1/movies/count?context=edit:1

**Comment by meugamer** [comment]
in wp-admin/admin.php?page=wpmovielibrary-movies&id=8&action=edit

jquery.js?ver=1.12.4:3 GET http://127.0.0.1/wp-content/plugins/wpmovielibrary/public/assets/img/loading.svg 404 (Not Found)
k @ jquery.js?ver=1.12.4:3
pixelMarginRight @ jquery.js?ver=1.12.4:3
Sa @ jquery.js?ver=1.12.4:3
css @ jquery.js?ver=1.12.4:3
set @ jquery.js?ver=1.12.4:3
style @ jquery.js?ver=1.12.4:3
(anonymous) @ jquery.js?ver=1.12.4:5
Y @ jquery.js?ver=1.12.4:3
n.fn.(anonymous function) @ jquery.js?ver=1.12.4:5
(anonymous) @ core.min.js?ver=1.11.4:11
(anonymous) @ core.min.js?ver=1.11.4:11
(anonymous) @ core.min.js?ver=1.11.4:11
jquery.js?ver=1.12.4:4 GET http://127.0.0.1/wp-json/wpmoly/v1/movie/8?context=embed 404 (Not Found)
send @ jquery.js?ver=1.12.4:4
ajax @ jquery.js?ver=1.12.4:4
e.ajax @ backbone.min.js?ver=1.2.3:1
e.sync @ backbone.min.js?ver=1.2.3:1
sync @ wp-api.js?ver=4.9.8:880
fetch @ backbone.min.js?ver=1.2.3:1
(anonymous) @ movie-editor.js?ver=3.0.0-beta:89
_ @ backbone.min.js?ver=1.2.3:1
m @ backbone.min.js?ver=1.2.3:1
f @ backbone.min.js?ver=1.2.3:1
u.trigger @ backbone.min.js?ver=1.2.3:1
t.success @ backbone.min.js?ver=1.2.3:1
i @ jquery.js?ver=1.12.4:2
fireWith @ jquery.js?ver=1.12.4:2
y @ jquery.js?ver=1.12.4:4
c @ jquery.js?ver=1.12.4:4
XMLHttpRequest.send (async)
send @ jquery.js?ver=1.12.4:4
ajax @ jquery.js?ver=1.12.4:4
e.ajax @ backbone.min.js?ver=1.2.3:1
e.sync @ backbone.min.js?ver=1.2.3:1
sync @ wp-api.js?ver=4.9.8:880
fetch @ backbone.min.js?ver=1.2.3:1
Editor @ movie-editor.js?ver=3.0.0-beta:101
MovieEditor.loadEditor @ movie-editor.js?ver=3.0.0-beta:4776
(anonymous) @ movie-editor.js?ver=3.0.0-beta:4792
i @ jquery.js?ver=1.12.4:2
add @ jquery.js?ver=1.12.4:2
MovieEditor.run @ movie-editor.js?ver=3.0.0-beta:4791
(anonymous) @ wpmoly.js?ver=3.0.0-beta:285
m.each.m.forEach @ underscore.min.js?ver=1.8.3:5
wpmoly.run @ wpmoly.js?ver=3.0.0-beta:284
(anonymous) @ wpmoly.js?ver=3.0.0-beta:294
i @ jquery.js?ver=1.12.4:2
fireWith @ jquery.js?ver=1.12.4:2
ready @ jquery.js?ver=1.12.4:2
K @ jquery.js?ver=1.12.4:2
VM1719:1 Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.notify (wpmoly.js?ver=3.0.0-beta:134)
    at Object.error (wpmoly.js?ver=3.0.0-beta:269)
    at n.error (movie-editor.js?ver=3.0.0-beta:1797)
    at _ (backbone.min.js?ver=1.2.3:1)
    at m (backbone.min.js?ver=1.2.3:1)
    at f (backbone.min.js?ver=1.2.3:1)
    at n.u.trigger (backbone.min.js?ver=1.2.3:1)
    at B.e.error (backbone.min.js?ver=1.2.3:1)
    at Object.n.error (backbone.min.js?ver=1.2.3:1)

**Comment by CaerCam** [comment]
Ok, now that looks like a server config issue, `public/assets/img/loading.svg` should be accessible.

Another hint: are you using WordPress' default permalinks settings (ie. 'Plain')?

**Comment by CaerCam** [comment]
@meugamer @kebekois Does the last commit fix the issue?

**Comment by kebekois** [comment]
Yes workin now.. my problem simple permalien !!

**Comment by meugamer** [comment]
The grid part seems to have solved. However, the movies still continues with the same problem. The permanent links . I'm using simply from wpmovie itself.

**Comment by CaerCam** [comment]
OK. The fact that the `loading.svg` file gets a 404 is weird. Can you access `http://127.0.0.1/wp-json/wpmoly/v1`, or does this also return 404?

**Comment by meugamer** [comment]
Error 
![image](https://user-images.githubusercontent.com/31143546/44962455-2bcfe480-aef7-11e8-8ad7-a55fdfb6c9df.png)

**Comment by CaerCam** [comment]
Ok. So it's not a permalink issue? `http://127.0.0.1/wp-json/wp/v2` for instance works as expected?

**Comment by meugamer** [comment]
Sorry for yesterday. The error is coming exactly from the permalink links.

**Comment by CaerCam** [comment]
No problem ;)
