### ISSUE TITLE
Add Categories/Tags support

### ISSUE THREAD

**Issue by CaerCam** [wpmovielibrary/wpmovielibrary#414]
Categories and Tags can be enabled for movies, but the movie editor does not have any block to handle these taxonomies.

Report @zack06007

**Comment by meugamer** [comment]
Caer, talking to some people who use the plugin. We arrived at a consensus that would be interesting. If the actors, directors, producers, writers, all were within the same taxonomy, or an alias for person. Example:
/ person /
Even if there was a separation by the type of profession. But if you rewrite it, you have to add them all in the same tag. Do not you think that would be interesting?
I even tried to leave everyone in the same taxonomy. But unfortunately, it ends up overlapping the taxonomy and presents error 404. or the taxonomy is duplicating the directors in actor and also in collection. I think it would be something of a general interest.

**Comment by CaerCam** [comment]
Don't worry, I'm actually planning something like that :) I first thought of using a single taxonomy, but we have to consider people with multiple jobs: most actors also have some directing, producing or writing experience, so we need separate taxonomies for each job.

The best solution I can think of is using taxonomies for jobs (among others) along with posts for detailed person data. When done with updating/fixing the existing I'll add a "Person" custom post type that will make it possible to download person metadata/images from TMDb just like movies'; "person" posts will be linked to "actor" and "collection" taxonomies using a single term metadata. In a second time I'll transfer all compatible movie metadata to taxonomies to lessen the database impact of the plugin; that includes every cast/credit entry (actors, directors, producers, editors, ...) but also production companies, languages, countries, ratings, subtitles... I didin't include this in version 3.0.0 because I thought a complete rewrite was enough trouble on itself to avoid adding giant changes in the data without discussing with the users :)

I'll open a new ticket soon to sum up and discuss what's planned.

**Comment by meugamer** [comment]
Thx =)!

I will translate and revise the Portuguese language version of the plugin. And then I send you!
