### ISSUE TITLE
Plugin doesnt work after PHP update to 7.0.30 

### ISSUE THREAD

**Issue by armando-coelho** [wpmovielibrary/wpmovielibrary#415]
Hi,

After PHP update can reach any data from imdb, on logs i found this errors:

2018/09/03 14:08:03 [error] 28830#28830: *146340 FastCGI sent in stderr: "PHP message: PHP Warning:  call_user_func_array() expects parameter 1 to be a valid callback, function 'meks_disable_srcset' not found or invalid function name in wp-includes/class-wp-hook.php on line 288
PHP message: PHP Warning:  explode() expects parameter 2 to be string, object given in wpmovielibrary/includes/classes/class-wpmoly-utils.php on line 889
PHP message: PHP Warning:  Invalid argument supplied for foreach() in wpmovielibrary/includes/classes/class-wpmoly-utils.php on line 891
PHP message: PHP Warning:  call_user_func_array() expects parameter 1 to be a valid callback, function 'meks_disable_srcset' not found or invalid function name in wp-includes/class-wp-hook.php on line 288
PHP message: PHP Warning:  call_user_func_array() expects parameter 1 to be a valid callback, function 'meks_disable_srcset' not found or invalid function name in wp-includes/class-wp-hook.php on line 288" while reading response header from upstream, client: 54.36.149.39, server: , request: "GET /movies/arrival/ HTTP/1.1", upstream: "fastcgi://127.0.0.1:9002", host: ""

**Comment by meugamer** [comment]
Hello the new wpmovie has been coded to work from version 7.2.0 onwards. It was described on dev's own blog.

**Comment by armando-coelho** [comment]
I'm using the version 2.1.4.7.

If i install the new one it comes with empty menus...

**Comment by meugamer** [comment]
I have wpmovie 2.1.7, and I use it together with nginx perfectly.

**Comment by armando-coelho** [comment]
since i made the php update have the errors that i post :/

**Comment by CaerCam** [comment]
Hi @armando-coelho, could you try adding `var_dump( $data );` in the `wpmovielibrary/includes/classes/class-wpmoly-utils.php`, line 889, right before `$_data = explode( ',', $data );`, so we can see what's wrong with the data?

**Comment by Daringbaaz** [comment]
Hi, When I Installed Latest Version, It Show Me Empty Menu.. Please Help Me to Solve This Problem..
I had Installed older Version and Its Doesn't Show Complete View ( Maybe Any Compatibility Issue)
