### ISSUE TITLE
Actors/Collections TMDb profile picture

### ISSUE THREAD

**Issue by caercam** [wpmovielibrary/wpmovielibrary#428]
Allow users to select a custom thumbnail from TMDb pictures for actors and collections based on people TMDb ID.

**Comment by meugamer** [comment]
Caer, I thought it would be interesting if you could import the character's name that the actor starred in the film. Or a field to be added manually depending on the language the person is importing. What do you think of that idea?

**Comment by CaerCam** [comment]
I've thought about it, but it raises some questions. How to handle translations? How to store the characters names to minimize the size in the database but keep it simple to use? Eventually [credits and cast will evolve to become taxonomies](https://github.com/wpmovielibrary/wpmovielibrary/issues/414#issuecomment-418523555), so it would make sense to use a taxonomy for characters two, but then unlike people you may want to support duplicate characters, something taxonomies don't handle well… Guess we'll have to see this thoroughly in a dedicated issue :)

**Comment by meugamer** [comment]
Caer, to pull the image of the actors straight into the taxonomy actor. Do I need a specific function? Or can I do this using the wordpress's own pattern with the image?

**Comment by meugamer** [comment]
I've been testing the plugin. I noticed the permanent links to actors among others. They do not seem to work properly. Only when it's for a movie that works. But when it is for actors it appears as:
site / movies / name-of-actor

**Comment by CaerCam** [comment]
Postponing this to 3.1.0 to focus on `person` post type (#442).

**Comment by awardscircuit** [comment]
> Postponing this to 3.1.0 to focus on `person` post type (#442).

Hey CaerCam.  Great plugin. Wanted to see if there was an update on the "person" post type for 3.1.0 version?
