### ISSUE TITLE
Movie not found in search (2.1.4.7)

### ISSUE THREAD

**Issue by dausruddin** [wpmovielibrary/wpmovielibrary#437]
Hi. I am using wpMovieLibrary 2.1.4.7

I am trying to load this movie (https://www.themoviedb.org/movie/515596-honey). But it doesn't appear in search.

**Comment by Gunnar-GO** [comment]
Maybe cause it's not the original title. If you copy the title from your link: ハニー it appears as first.

**Comment by dausruddin** [comment]
Since this is an old issue (almost a year), I already forgot the details. I should have included some examples and more details. For now, I'll close this.
