### ISSUE TITLE
Importation en masse

### ISSUE THREAD

**Issue by Steffi3rd** [wpmovielibrary/wpmovielibrary#439]
Hello, 

Je viens d'installer ce super plugin pour pouvoir stocker des films en base et les afficher sur mon site. C'est vraiment du bon travail.

J'ai cependant quelques questions sur l'importation.

1 - Comment faire pour ajouter plusieurs films avec un seul titre ? 

Exemple : En cherchant IP Man, je souhaite ajouter tous les IP Man (1, 2 ,3 ,4 et les autres IP Man trouvés), au lieu de sélectionner un seul film parmi la liste. 

2 - Y a-t-il un moyen, d'avoir une liste de films séparés par les virgules, sans qu'on a les écrire un par un ? 

Exemple : pouvoir "générer" une liste de tous les films de Scarlett Johansson séparés dans des virgules et le mettre dans le champs de titre.

3 - Y a-t-il un moyen d'importer nos films favoris de notre compte TMDB ? En utilisant notre clé API déjà renseignée ? 

Je pose ces questions car j'essaye d'importer rapidement mais en 20 minutes, j'en ai importé que quelques uns... Du coup, si je veux ajouter les films de tous mes acteurs préférés, je vais mettre vraiment beaucoup de temps.

Merci !

**Comment by CaerCam** [comment]
En l'état il n'est pas possible de gérer des listes de titres avec la version 3.0, mais c'est prévu, je réfléchis au meilleur moyen de mettre ça en place, soit directement via le champ « Ajouter un nouveau film » soit via un outil plus spécifique… Mais ça reste l'une (sinon *la*) principale fonctionnalité du plugin, donc pas question de l'oublier !

Pour ce qui est des films favoris, j'y pense depuis le début du plugin, mais je n'ai jamais eu le temps de m'y atteler. Je garde ça sous le coude pour quand les fonctionnalités les plus importantes seront bouclées :)

**Comment by Steffi3rd** [comment]
Super bonne nouvelle ! 

Hâte de voir ces fonctionnalités.
