### ISSUE TITLE
Ajouter ID actor lors de l’importation Des acteurs 

### ISSUE THREAD

**Issue by Steffi3rd** [wpmovielibrary/wpmovielibrary#440]
Bonjour,

Est-il possible de pouvoir ajouter l’ID de l’acteur lorsqu’il est importé depuis un film ? 

Aujourd’hui dans la page acteur, on a uniquement nom et slug.

Est-ce Qu’il y a un moyen d’ajouter au moins l’ID, même si l’deal serait d’avoir les autres champs comme Avatar, Birthday, Sex Etc.  

Merci !

**Comment by CaerCam** [comment]
Bonjour @Steffi3rd,

Oui, c'est prévu : à terme les acteurs, réalisateurs et plus généralement tout ce qui concerne une personne physique sera géré via des taxonomies et non des métadonnées comme actuellement ; cela permettra de conserver l'ID TMDb de chaque personne et de la lier à une fiche individuelle pour la personne, via un nouveau type de contenu dédié, ce qui permettra alors bien plus de fonctionnalités : biographie détaillée, gestion de filmographie, etc :)

Il serait plus simple en apparence de gérer ces informations directement au niveau des taxonomies, mais le soucis est qu'une même personne peut être à la fois acteur, réalisateur et producteur d'un même film, ce qui voudrait dire trois termes identiques dans trois taxonomies différentes, ce qui a du sens, mais aussi trois jeux de métadonnées identiques en parallèle, ce qui n'a pas de sens… D'où ma préférence pour un outil tiers pour gérer ces données.

**Comment by Steffi3rd** [comment]
Ah c'est top ! 

Merci pour cette réponse détaillée !

Concernant la même personne qui peut avoir 3 rôles différents dans le même film, ne pourrait-on pas créer un Custom type "People" au lieu de Acteur ? Et plutôt gérer l'acteur en tant que taxonomie ? Il pourrait y avoir plusieurs taxonomie pour People dont Acteur/Réalisateur/Producteur

**Comment by CaerCam** [comment]
C'est exactement l'idée, oui :)

**Comment by CaerCam** [comment]
Implemented in b57c53e.

**Comment by Steffi3rd** [comment]
Trop vif ! 🚀
