### ISSUE TITLE
Website crashes

### ISSUE THREAD

**Issue by najlouu** [wpmovielibrary/wpmovielibrary#444]
My website crashed apparently because of the mp movie library pluggin.
Here's what the hosting company support wrote to me: 
"We have looked into this and the white screen is caused by the plugin wpbooklist-goodreads-1_backup. The error message with this is:

Warning: require_once(/home/sugoiaco/public_html/wp-content/plugins-1_backup/wpbooklist/includes/classes/translations/class-wpbooklist-translations.php): failed to open stream: No such file or directory in /home/sugoiaco/public_html/wp-content/plugins/wpbooklist-goodreads-1_backup/includes/class-goodreads-general-functions.php on line 376

Fatal error: require_once(): Failed opening required '/home/sugoiaco/public_html/wp-content/plugins-1_backup/wpbooklist/includes/classes/translations/class-wpbooklist-translations.php' (include_path='.:/opt/alt/php70/usr/share/pear') in /home/sugoiaco/public_html/wp-content/plugins/wpbooklist-goodreads-1_backup/includes/class-goodreads-general-functions.php on line 376

We have disabled the plugin folder by renaming the folder to have ".off". The folder can be found here: 

public_html/wp-content/plugins/wpbooklist-goodreads-1_backup.off

Can you help me fix this please? I am not a programmer and I have no idea what to do... 

Cheers,
Najla

**Comment by CaerCam** [comment]
Hi @najlouu,

Your crash is caused by the WordPress Book List plugin. You may want to report the issue directly to them over at https://wordpress.org/support/plugin/wpbooklist. They seem to have tech support email too: techsupport@wpbooklist.com.
