### ISSUE TITLE
could not resolve tmdb.caercam.org

### ISSUE THREAD

**Issue by adamcodes716** [wpmovielibrary/wpmovielibrary#457]
Hello, is this endpoint no longer valid?

**Comment by adamcodes716** [comment]
I enabled tmdb api in "Settings" and I no longer have this problem anymore

**Comment by caercam** [comment]
Yeah, I had to remove that subdomain due to some stupid hosting policy, the last update of the plugin switched to https://api.wplibraries.com

I'll probably update the API in the future to switch to a more recent framework, but for now it still does the job :)
