### ISSUE TITLE
Collection meta bug

### ISSUE THREAD

**Issue by zack06007** [wpmovielibrary/wpmovielibrary#461]
Salut Charlie,

J’espère que tu vas bien depuis le temps

Toujours en pleine utilisation de ton module, je voulais savoir pourquoi les "meta" collection (donc le réalisateur) ne sont plus ajoutés automatiquement dans la liste. A chaque fois je dois faire ajouter une nouvelle collection (ou chercher dans la liste) le nom du réalisateur. Alors qu'avant c'était tout automatique.

Pour les genres, acteurs, etc... là aucun souci.

Et comme je créer un second site sur le festival de Cannes, je voulais comprendre pourquoi la fonction n'est plus automatisée.

Au plaisir de te lire,
A très bientôt Charlie.

Jacques
![Sans titre](https://github.com/wpmovielibrary/wpmovielibrary/assets/8669357/8404d76b-afb6-4b70-9de7-64ce00236d41)

**Comment by zack06007** [comment]
De plus, ton plugin enlève les tags des categories sur la page d'accueil (sauf sur le premier post)
Ca aurait été bien que WPML ne les vire pas. 

En esperant que tu sois encore actif un peu ici
+++

**Comment by caercam** [comment]
Salut !

Effectivement les collections ne se mettaient plus à jour si on pas préalablement cliqué sur « Nouvelle collection », il semble que le fait que le champ dans lequel le nom du réalisateur est inséré ne fonctionne pas s'il est masqué. Autre soucis, la sélection d'une collection existante ne fonctionnait plus non plus, impossible d'ajouter automatiquement un nouveau film à une collection déjà créée. Du coup j'ai corrigé ça aussi, tu peux tester :)

**Comment by zack06007** [comment]
Charlie, tu es un génie je viens d'essayer avec tes deux nouveaux fichiers et ça semble fonctionné à la perfection - je me suis collé 200 fiches de films à entrer à chaque fois le réal. y a 5 jours à cause de ce petit bug. Au moins là ton plugin est parfait (déjà qu'il l'était !) Encore Merci et longue vie à tes projets

**Comment by caercam** [comment]
Super ! Je vais préparer une mise à jour pour le repo officiel du coup.

Ne le répète à personne, mais mon objectif est de sortir la version 4.0 au mois d'août… Moult péripéties ces dernières années, une sortie 11 ans pile poil après la première publication sur GitHub ça marquerait le coup ! Affaire à suivre :)

**Comment by zack06007** [comment]
Cool
J'espère que les options actuelles seront toujours présentes avec les méta etc... ;) en tout cas c'est super de faire vivre ce module que j'utilise tous les jours !

Merci encore pour le correctif

**Comment by caercam** [comment]
L'idée est justement de reprendre le plugin à zéro pour en écrire une version moderne, aux standards de dev d'aujourd'hui, sans commencer à ajouter tout et n'importe quoi comme fonctionnalités :) N'hésite pas à m'envoyer par mail une liste des options que tu veux impérativement garder, ça me permettra de vérifier que je n'oublie rien !

**Comment by zack06007** [comment]
Slt Charlie

Je pense que les métadonnées resteront pour être insérés directement sur les articles/movie.
 
Après.je vous pas trop ce qui n'est pas indispensable. Le menu (archive) qui référence tous les films est génial a ne pas oublier aussi 

Je verrai la nouvelle version et te dirait ce qui a disparu et était bien !

La j'ai fais un second site avec ton module y a juste une erreur sur l'affichage des catégories sur l'accueil qui est mal généré par WPML. Mais on en reparlera, en attendant j'ai réussi a masquer ce souci par un correctif CSS/module additionnel.

Pour mon premier site aucun souci car pas de catégorie.

Après.je.pzux être ton beta testeur par whatapp ou autre. En tout cas ce module c'est génial, je viens encore de l'expliquer a une commission du rectorat ce matin. Faut que ça soit simple pour eux et c'est le cas.
