### ISSUE TITLE
Améliorations

### ISSUE THREAD

**Issue by lesurfeur** [wpmovielibrary/wpmovielibrary#71]
Quelques idées d'amélioration : 
- ~~Franciser (internationaliser) les pays.~~ --> Ok avec la V2
- ~~Franciser (internationaliser) les langues.~~ --> Ok avec la V2
- ~~Pouvoir trier par année de réalisation.~~ --> Ok avec la V2
- Trouver autre chose que la virgule pour séparer les films dans "importer des films" car pas mal de titres la possède et cela génère deux titres dans "films importés". (gênant lors de gros import)
- Exporter sa liste (titres), au moins en format texte.
- ~~Possibilité de rajouter / supprimer des médias.~~ --> Ok avec la V2
- ~~Sélection multiple des médias. (lorsque l'on possède par ex. un dvd et un blu-ray du même film)~~ --> Ok avec la V2
- ~~Pouvoir choisir "Aucun" pour les sous titres.~~ -->Ok https://github.com/wpmovielibrary/wpmovielibrary/issues/71#issuecomment-75429418

Suite au lancement des plugins en aôut :
- un plugin pour afficher les films similaires sous une fiche de film cela serait pas mal. J'ai testé plusieurs plugin du genre (gratuit) mais aucun ne prend en charge les CPT (ou si il y en a ils ne sont plus jours ex: Related Posts via Taxonomies).
- ~~un plugin pour une meilleur recherche (ou une modif pour le moteur de recherche a mettre dans function.php du thème) qui prendrait en charge les custom fields. Dans le cas présent, si je fais une recherche avec le nom d'un acteur par exemple, cela ne trouve rien. (j'ai testé Search Everything, pas mal mais des bugs)~~ --> Ok avec la V2

Je rajouterai au fur et à mesure sur ce topic.

**Comment by lesurfeur** [comment]
Maj
--> Pouvoir choisir "Aucun" pour les sous titres.

**Comment by CaerCam** [comment]
Ajouté :)

**Comment by lesurfeur** [comment]
Merci Charlie.
Cela sera mieux que d'avoir un tiret, car on ne savait pas si on ne l'avais pas renseigné ou s'il n'y en avait pas. ;)

**Comment by CaerCam** [comment]
Ah du coup je viens de voir que j'ai mis "aucun" comme valeur par défaut, pas forcément une bonne idée, je modifierai ça.

**Comment by lesurfeur** [comment]
Quand on selectionne aucun, le "aucun" ne s'affiche pas sur la page du film.
![capture](https://cloud.githubusercontent.com/assets/5854465/6651092/33e9b0fc-ca34-11e4-9c48-04cd549875f5.PNG)
